/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'
import * as HypercertsDefs from '../defs.defs'

const $nsid = 'org.hypercerts.context.acknowledgement'

export { $nsid }

/** Acknowledges a record (subject) or its relationship in a context. Created in the acknowledging actor's repo to form a bidirectional link. Examples: a contributor acknowledging inclusion in an activity, an activity owner acknowledging inclusion in a collection, or a record owner acknowledging an evaluation. */
type Main = {
  $type: 'org.hypercerts.context.acknowledgement'

  /**
   * The record being acknowledged (e.g. an activity, a contributor information record, an evaluation).
   */
  subject: RepoStrongRef.Main

  /**
   * Context for the acknowledgement (e.g. the collection that includes an activity, or the activity that includes a contributor). A URI for a lightweight reference or a strong reference for content-hash verification.
   */
  context?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject

  /**
   * Whether the relationship is acknowledged (true) or rejected (false).
   */
  acknowledged: boolean

  /**
   * Optional plain-text comment providing additional context or reasoning.
   */
  comment?: string

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Acknowledges a record (subject) or its relationship in a context. Created in the acknowledging actor's repo to form a bidirectional link. Examples: a contributor acknowledging inclusion in an activity, an activity owner acknowledging inclusion in a collection, or a record owner acknowledging an evaluation. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subject: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    context: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
    acknowledged: l.boolean(),
    comment: l.optional(l.string({ maxLength: 10000, maxGraphemes: 1000 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
