/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'
import * as HypercertsDefs from '../defs.defs'
import * as RichtextFacet from '../../../app/bsky/richtext/facet.defs'
import * as PagesLinearDocument from '../../../pub/leaflet/pages/linearDocument.defs'

const $nsid = 'org.hypercerts.context.attachment'

export { $nsid }

/** An attachment providing commentary, context, evidence, or documentary material related to a hypercert record (e.g. an activity, project, claim, or evaluation). */
type Main = {
  $type: 'org.hypercerts.context.attachment'

  /**
   * References to the subject(s) the attachment is connected to—this may be an activity claim, outcome claim, measurement, evaluation, or even another attachment. This is optional as the attachment can exist before the claim is recorded.
   */
  subjects?: RepoStrongRef.Main[]

  /**
   * The type of attachment, e.g. report, audit, evidence, testimonial, methodology, etc.
   */
  contentType?: string

  /**
   * The files, documents, or external references included in this attachment record.
   */
  content?: (
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallBlob>
    | l.Unknown$TypedObject
  )[]

  /**
   * Display title for this attachment (e.g. 'Impact Assessment Report', 'Audit Findings')
   */
  title: string

  /**
   * Short summary of this attachment, suitable for previews and list views. Rich text annotations may be provided via `shortDescriptionFacets`.
   */
  shortDescription?: string

  /**
   * Rich text annotations for `shortDescription` (mentions, URLs, hashtags, etc).
   */
  shortDescriptionFacets?: RichtextFacet.Main[]

  /**
   * Rich-text description, represented as a Leaflet linear document.
   */
  description?: PagesLinearDocument.Main

  /**
   * A strong reference to the location where this attachment's subject matter occurred. The record referenced must conform with the lexicon app.certified.location.
   */
  location?: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** An attachment providing commentary, context, evidence, or documentary material related to a hypercert record (e.g. an activity, project, claim, or evaluation). */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subjects: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 100,
      }),
    ),
    contentType: l.optional(l.string({ maxLength: 64 })),
    content: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
            l.typedRef<HypercertsDefs.SmallBlob>(
              (() => HypercertsDefs.smallBlob) as any,
            ),
          ],
          false,
        ),
        { maxLength: 100 },
      ),
    ),
    title: l.string({ maxLength: 256 }),
    shortDescription: l.optional(
      l.string({ maxLength: 3000, maxGraphemes: 300 }),
    ),
    shortDescriptionFacets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
    description: l.optional(
      l.ref<PagesLinearDocument.Main>((() => PagesLinearDocument.main) as any),
    ),
    location: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
