/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'
import * as CertifiedDefs from '../../../app/certified/defs.defs'
import * as RichtextFacet from '../../../app/bsky/richtext/facet.defs'

const $nsid = 'org.hypercerts.context.measurement'

export { $nsid }

/** Measurement data related to one or more records (e.g. activities, projects, etc.). */
type Main = {
  $type: 'org.hypercerts.context.measurement'

  /**
   * Strong references to the records this measurement refers to (e.g. activities, projects, or claims).
   */
  subjects?: RepoStrongRef.Main[]

  /**
   * The metric being measured, e.g. forest area restored, number of users, etc.
   */
  metric: string

  /**
   * The unit of the measured value (e.g. kg CO₂e, hectares, %, index score).
   */
  unit: string

  /**
   * The measured value as a numeric string (e.g. '1234.56')
   */
  value: string

  /**
   * The start date and time when the measurement began.
   */
  startDate?: l.DatetimeString

  /**
   * The end date and time when the measurement ended. For one-time measurements, this should equal the start date.
   */
  endDate?: l.DatetimeString

  /**
   * Optional geographic references related to where the measurement was taken. Each referenced record must conform with the app.certified.location lexicon.
   */
  locations?: RepoStrongRef.Main[]

  /**
   * Short identifier for the measurement methodology
   */
  methodType?: string

  /**
   * URI to methodology documentation, standard protocol, or measurement procedure
   */
  methodURI?: l.UriString

  /**
   * URIs to related evidence or underlying data (e.g. org.hypercerts.claim.evidence records or raw datasets)
   */
  evidenceURI?: l.UriString[]

  /**
   * DIDs of the entities that performed this measurement
   */
  measurers?: CertifiedDefs.Did[]

  /**
   * Short comment of this measurement, suitable for previews and list views. Rich text annotations may be provided via `commentFacets`.
   */
  comment?: string

  /**
   * Rich text annotations for `comment` (mentions, URLs, hashtags, etc).
   */
  commentFacets?: RichtextFacet.Main[]

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Measurement data related to one or more records (e.g. activities, projects, etc.). */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subjects: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 100,
      }),
    ),
    metric: l.string({ maxLength: 500 }),
    unit: l.string({ maxLength: 50 }),
    value: l.string({ maxLength: 500 }),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
    locations: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 100,
      }),
    ),
    methodType: l.optional(l.string({ maxLength: 30 })),
    methodURI: l.optional(l.string({ format: 'uri' })),
    evidenceURI: l.optional(
      l.array(l.string({ format: 'uri' }), { maxLength: 50 }),
    ),
    measurers: l.optional(
      l.array(l.ref<CertifiedDefs.Did>((() => CertifiedDefs.did) as any), {
        maxLength: 100,
      }),
    ),
    comment: l.optional(l.string({ maxLength: 3000, maxGraphemes: 300 })),
    commentFacets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
