/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from '../../../app/bsky/richtext/facet.defs'
import * as PagesLinearDocument from '../../../pub/leaflet/pages/linearDocument.defs'
import * as HypercertsDefs from '../defs.defs'
import * as WorkscopeCel from '../workscope/cel.defs'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'

const $nsid = 'org.hypercerts.claim.activity'

export { $nsid }

/** A hypercert record tracking impact work. */
type Main = {
  $type: 'org.hypercerts.claim.activity'

  /**
   * Display title summarizing the impact work (e.g. 'Reforestation in Amazon Basin 2024')
   */
  title: string

  /**
   * Short summary of this activity claim, suitable for previews and list views. Rich text annotations may be provided via `shortDescriptionFacets`.
   */
  shortDescription: string

  /**
   * Rich text annotations for `shortDescription` (mentions, URLs, hashtags, etc).
   */
  shortDescriptionFacets?: RichtextFacet.Main[]

  /**
   * Rich-text description, represented as a Leaflet linear document.
   */
  description?: PagesLinearDocument.Main

  /**
   * The hypercert visual representation as a URI or image blob.
   */
  image?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * An array of contributor objects, each containing contributor information, weight, and contribution details.
   */
  contributors?: Contributor[]

  /**
   * Work scope definition. A CEL expression for structured, machine-evaluable scopes or a free-form string for simple and legacy scopes.
   */
  workScope?:
    | l.$Typed<WorkscopeCel.Main>
    | l.$Typed<WorkScopeString>
    | l.Unknown$TypedObject

  /**
   * When the work began
   */
  startDate?: l.DatetimeString

  /**
   * When the work ended
   */
  endDate?: l.DatetimeString

  /**
   * An array of strong references to the location where activity was performed. The record referenced must conform with the lexicon app.certified.location.
   */
  locations?: RepoStrongRef.Main[]

  /**
   * A strong reference to the rights that this hypercert has. The record referenced must conform with the lexicon org.hypercerts.claim.rights.
   */
  rights?: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A hypercert record tracking impact work. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    title: l.string({ maxLength: 256 }),
    shortDescription: l.string({ maxLength: 3000, maxGraphemes: 300 }),
    shortDescriptionFacets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
    description: l.optional(
      l.ref<PagesLinearDocument.Main>((() => PagesLinearDocument.main) as any),
    ),
    image: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    contributors: l.optional(
      l.array(l.ref<Contributor>((() => contributor) as any), {
        maxLength: 1000,
      }),
    ),
    workScope: l.optional(
      l.typedUnion(
        [
          l.typedRef<WorkscopeCel.Main>((() => WorkscopeCel.main) as any),
          l.typedRef<WorkScopeString>((() => workScopeString) as any),
        ],
        false,
      ),
    ),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
    locations: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 1000,
      }),
    ),
    rights: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Contributor = {
  $type?: 'org.hypercerts.claim.activity#contributor'

  /**
   * Inline contributor identity object with an identity string (DID or identifier) via org.hypercerts.claim.activity#contributorIdentity, or a strong reference to a contributor information record. The record referenced must conform with the lexicon org.hypercerts.claim.contributorInformation.
   */
  contributorIdentity:
    | l.$Typed<ContributorIdentity>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject

  /**
   * The relative weight/importance of this contribution (stored as a string to avoid float precision issues). Must be a positive numeric value. Weights do not need to sum to a specific total; normalization can be performed by the consuming application as needed.
   */
  contributionWeight?: string

  /**
   * Inline contribution role object with a role string via org.hypercerts.claim.activity#contributorRole, or a strong reference to a contribution details record. The record referenced must conform with the lexicon org.hypercerts.claim.contribution.
   */
  contributionDetails?:
    | l.$Typed<ContributorRole>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
}

export type { Contributor }

const contributor = l.typedObject<Contributor>(
  $nsid,
  'contributor',
  l.object({
    contributorIdentity: l.typedUnion(
      [
        l.typedRef<ContributorIdentity>((() => contributorIdentity) as any),
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
      ],
      false,
    ),
    contributionWeight: l.optional(l.string({ maxLength: 100 })),
    contributionDetails: l.optional(
      l.typedUnion(
        [
          l.typedRef<ContributorRole>((() => contributorRole) as any),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { contributor }

/** Contributor information as a string (DID or identifier). */
type ContributorIdentity = {
  $type?: 'org.hypercerts.claim.activity#contributorIdentity'

  /**
   * The contributor identity string (DID or identifier).
   */
  identity: string
}

export type { ContributorIdentity }

/** Contributor information as a string (DID or identifier). */
const contributorIdentity = l.typedObject<ContributorIdentity>(
  $nsid,
  'contributorIdentity',
  l.object({ identity: l.string({ maxLength: 1000, maxGraphemes: 100 }) }),
)

export { contributorIdentity }

/** Contribution details as a string. */
type ContributorRole = {
  $type?: 'org.hypercerts.claim.activity#contributorRole'

  /**
   * The contribution role or details.
   */
  role: string
}

export type { ContributorRole }

/** Contribution details as a string. */
const contributorRole = l.typedObject<ContributorRole>(
  $nsid,
  'contributorRole',
  l.object({ role: l.string({ maxLength: 1000, maxGraphemes: 100 }) }),
)

export { contributorRole }

/** A free-form string describing the work scope for simple or legacy scopes. */
type WorkScopeString = {
  $type?: 'org.hypercerts.claim.activity#workScopeString'

  /**
   * The work scope description string.
   */
  scope: string
}

export type { WorkScopeString }

/** A free-form string describing the work scope for simple or legacy scopes. */
const workScopeString = l.typedObject<WorkScopeString>(
  $nsid,
  'workScopeString',
  l.object({ scope: l.string({ maxLength: 1000, maxGraphemes: 100 }) }),
)

export { workScopeString }
