/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../defs.defs'

const $nsid = 'org.hypercerts.claim.contributorInformation'

export { $nsid }

/** Contributor information including identifier, display name, and image. */
type Main = {
  $type: 'org.hypercerts.claim.contributorInformation'

  /**
   * DID (did:plc:...) or URI to a social profile of the contributor.
   */
  identifier?: string

  /**
   * Human-readable name for the contributor as it should appear in UI.
   */
  displayName?: string

  /**
   * The contributor visual representation as a URI or image blob.
   */
  image?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Contributor information including identifier, display name, and image. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    identifier: l.optional(l.string({ maxLength: 2048 })),
    displayName: l.optional(l.string({ maxLength: 100 })),
    image: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
