/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.hypercerts.claim.contribution'

export { $nsid }

/** Details about a specific contribution including role, description, and timeframe. */
type Main = {
  $type: 'org.hypercerts.claim.contribution'

  /**
   * Role or title of the contributor.
   */
  role?: string

  /**
   * Description of what the contribution concretely involved.
   */
  contributionDescription?: string

  /**
   * When this contribution started. Should fall within the parent hypercert's timeframe.
   */
  startDate?: l.DatetimeString

  /**
   * When this contribution finished. Should fall within the parent hypercert's timeframe.
   */
  endDate?: l.DatetimeString

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Details about a specific contribution including role, description, and timeframe. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    role: l.optional(l.string({ maxLength: 100 })),
    contributionDescription: l.optional(
      l.string({ maxLength: 10000, maxGraphemes: 1000 }),
    ),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
