/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../defs.defs'

const $nsid = 'org.hypercerts.claim.rights'

export { $nsid }

/** Describes the rights that a contributor and/or an owner has, such as whether the hypercert can be sold, transferred, and under what conditions. */
type Main = {
  $type: 'org.hypercerts.claim.rights'

  /**
   * Human-readable name for these rights (e.g. 'All Rights Reserved', 'CC BY-SA 4.0')
   */
  rightsName: string

  /**
   * Short identifier code for this rights type (e.g. 'ARR', 'CC-BY-SA') to facilitate filtering and search
   */
  rightsType: string

  /**
   * Detailed explanation of the rights holders' permissions, restrictions, and conditions
   */
  rightsDescription: string

  /**
   * An attachment to define the rights further, e.g. a legal document.
   */
  attachment?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallBlob>
    | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Describes the rights that a contributor and/or an owner has, such as whether the hypercert can be sold, transferred, and under what conditions. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    rightsName: l.string({ maxLength: 100 }),
    rightsType: l.string({ maxLength: 10 }),
    rightsDescription: l.string({ maxLength: 10000, maxGraphemes: 1000 }),
    attachment: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallBlob>(
            (() => HypercertsDefs.smallBlob) as any,
          ),
        ],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
