/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.organization.defaultSite'

export { $nsid }

/** A declaration of the default site for an organization */
type Main = {
  $type: 'app.gainforest.organization.defaultSite'

  /**
   * The reference to the default site record in the PDS
   */
  site: l.AtUriString

  /**
   * The date and time of the creation of the record
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A declaration of the default site for an organization */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    site: l.string({ format: 'at-uri' }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
