/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommonDefs from '../common/defs.defs'

const $nsid = 'app.gainforest.organization.getIndexedOrganizations'

export { $nsid }

/** Get all organizations to view initially on map */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    organizations: l.array(
      l.ref<CommonDefs.IndexedOrganization>(
        (() => CommonDefs.indexedOrganization) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
