/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommonDefs from '../common/defs.defs'
import * as PagesLinearDocument from '../../../pub/leaflet/pages/linearDocument.defs'
import * as HypercertsDefs from '../../../org/hypercerts/defs.defs'

const $nsid = 'app.gainforest.organization.info'

export { $nsid }

/** A declaration of an organization or project */
type Main = {
  $type: 'app.gainforest.organization.info'

  /**
   * The name of the organization or project
   */
  displayName: string

  /**
   * The description of the organization or project
   */
  shortDescription: CommonDefs.Richtext

  /**
   * The long description of the organization or project in richtext
   */
  longDescription: PagesLinearDocument.Main

  /**
   * Cover image for the organization
   */
  coverImage?: HypercertsDefs.SmallImage

  /**
   * Logo for the organization
   */
  logo?: HypercertsDefs.SmallImage

  /**
   * The objectives of the organization or project
   */
  objectives: (
    | 'Conservation'
    | 'Research'
    | 'Education'
    | 'Community'
    | 'Other'
  )[]

  /**
   * The start date of the organization or project
   */
  startDate?: l.DatetimeString

  /**
   * The website of the organization or project
   */
  website?: l.UriString

  /**
   * The country of the organization or project in two letter code (ISO 3166-1 alpha-2)
   */
  country: string

  /**
   * The visibility of the organization or project in the Green Globe
   */
  visibility: 'Public' | 'Unlisted'

  /**
   * The date and time of the creation of the record
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A declaration of an organization or project */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    displayName: l.string({ minLength: 8, maxLength: 255 }),
    shortDescription: l.ref<CommonDefs.Richtext>(
      (() => CommonDefs.richtext) as any,
    ),
    longDescription: l.ref<PagesLinearDocument.Main>(
      (() => PagesLinearDocument.main) as any,
    ),
    coverImage: l.optional(
      l.ref<HypercertsDefs.SmallImage>(
        (() => HypercertsDefs.smallImage) as any,
      ),
    ),
    logo: l.optional(
      l.ref<HypercertsDefs.SmallImage>(
        (() => HypercertsDefs.smallImage) as any,
      ),
    ),
    objectives: l.array(
      l.enum(['Conservation', 'Research', 'Education', 'Community', 'Other']),
    ),
    startDate: l.optional(l.string({ format: 'datetime' })),
    website: l.optional(l.string({ format: 'uri' })),
    country: l.string(),
    visibility: l.enum(['Public', 'Unlisted']),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
