/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.bumicerts.link.evm'

export { $nsid }

/** A verifiable link between an ATProto DID and an EVM wallet address, with platform attestation. The user proves wallet ownership via EIP-712 signature, and the platform co-signs to attest the linking occurred through a trusted service. */
type Main = {
  $type: 'app.bumicerts.link.evm'

  /**
   * Optional user-defined name for this wallet link (e.g. 'Personal Wallet', 'Project Treasury'). Helps users identify which wallet this record represents when they have multiple linked wallets.
   */
  name?: string

  /**
   * EVM wallet address (0x-prefixed, checksummed).
   */
  address: string

  /**
   * User's cryptographic proof of wallet ownership. Open union to support future signature methods (ERC-1271, ERC-6492).
   */
  userProof: l.$Typed<Eip712Proof> | l.Unknown$TypedObject

  /**
   * Platform's co-signature attesting that this link was created through the trusted service. Open union to support future attestation methods.
   */
  platformAttestation:
    | l.$Typed<Eip712PlatformAttestation>
    | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A verifiable link between an ATProto DID and an EVM wallet address, with platform attestation. The user proves wallet ownership via EIP-712 signature, and the platform co-signs to attest the linking occurred through a trusted service. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    name: l.optional(l.string({ maxLength: 100 })),
    address: l.string({ minLength: 42, maxLength: 42 }),
    userProof: l.typedUnion(
      [l.typedRef<Eip712Proof>((() => eip712Proof) as any)],
      false,
    ),
    platformAttestation: l.typedUnion(
      [
        l.typedRef<Eip712PlatformAttestation>(
          (() => eip712PlatformAttestation) as any,
        ),
      ],
      false,
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** EOA wallet ownership proof via EIP-712 typed data signature. */
type Eip712Proof = {
  $type?: 'app.bumicerts.link.evm#eip712Proof'

  /**
   * User's ECDSA signature over the EIP-712 hash (hex-encoded with 0x prefix, 64 or 65 bytes).
   */
  signature: string

  /**
   * The EIP-712 structured message fields that were signed.
   */
  message: Eip712Message
}

export type { Eip712Proof }

/** EOA wallet ownership proof via EIP-712 typed data signature. */
const eip712Proof = l.typedObject<Eip712Proof>(
  $nsid,
  'eip712Proof',
  l.object({
    signature: l.string({ minLength: 130, maxLength: 132 }),
    message: l.ref<Eip712Message>((() => eip712Message) as any),
  }),
)

export { eip712Proof }

/** The EIP-712 typed data message signed by the user's wallet. */
type Eip712Message = {
  $type?: 'app.bumicerts.link.evm#eip712Message'

  /**
   * The ATProto DID being linked to the EVM address.
   */
  did: l.DidString

  /**
   * The EVM wallet address (must match the top-level address field).
   */
  evmAddress: string

  /**
   * EVM chain ID as string (bigint serialized). The EIP-712 domain is chain-specific; verifiers should treat this attestation as valid only for the specified chain.
   */
  chainId: string

  /**
   * Unix timestamp when the attestation was created (bigint serialized).
   */
  timestamp: string

  /**
   * Replay-protection nonce (bigint serialized).
   */
  nonce: string
}

export type { Eip712Message }

/** The EIP-712 typed data message signed by the user's wallet. */
const eip712Message = l.typedObject<Eip712Message>(
  $nsid,
  'eip712Message',
  l.object({
    did: l.string({ format: 'did', maxLength: 256 }),
    evmAddress: l.string({ minLength: 42, maxLength: 42 }),
    chainId: l.string({ minLength: 1, maxLength: 78 }),
    timestamp: l.string({ minLength: 1, maxLength: 78 }),
    nonce: l.string({ minLength: 1, maxLength: 78 }),
  }),
)

export { eip712Message }

/** Platform's EIP-712 attestation that this DID-wallet link was created through a trusted service. The platform signs over the user's signature to bind its attestation to the specific linking event. */
type Eip712PlatformAttestation = {
  $type?: 'app.bumicerts.link.evm#eip712PlatformAttestation'

  /**
   * Platform's ECDSA signature over the signedData (hex-encoded with 0x prefix, 64 or 65 bytes).
   */
  signature: string

  /**
   * The platform's signing wallet address (0x-prefixed). Verifiers should check this against known/trusted platform addresses.
   */
  platformAddress: string

  /**
   * The user's signature that the platform signed over (hex-encoded with 0x prefix). This binds the platform attestation to the specific user proof.
   */
  signedData: string
}

export type { Eip712PlatformAttestation }

/** Platform's EIP-712 attestation that this DID-wallet link was created through a trusted service. The platform signs over the user's signature to bind its attestation to the specific linking event. */
const eip712PlatformAttestation = l.typedObject<Eip712PlatformAttestation>(
  $nsid,
  'eip712PlatformAttestation',
  l.object({
    signature: l.string({ minLength: 130, maxLength: 132 }),
    platformAddress: l.string({ minLength: 42, maxLength: 42 }),
    signedData: l.string({ minLength: 130, maxLength: 132 }),
  }),
)

export { eip712PlatformAttestation }
