/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CertifiedDefs from '../../../app/certified/defs.defs'

const $nsid = 'org.hypercerts.funding.receipt'

export { $nsid }

/** Records a funding receipt for a payment from one user to another user. It may be recorded by the recipient, by the sender, or by a third party. The sender may remain anonymous. */
type Main = {
  $type: 'org.hypercerts.funding.receipt'

  /**
   * DID of the sender who transferred the funds. Leave empty if sender wants to stay anonymous.
   */
  from: CertifiedDefs.Did

  /**
   * The recipient of the funds. Can be identified by DID or a clear-text name.
   */
  to: string

  /**
   * Amount of funding received as a numeric string (e.g. '1000.50').
   */
  amount: string

  /**
   * Currency of the payment (e.g. EUR, USD, ETH).
   */
  currency: string

  /**
   * How the funds were transferred (e.g. bank_transfer, credit_card, onchain, cash, check, payment_processor).
   */
  paymentRail?: string

  /**
   * Optional network within the payment rail (e.g. arbitrum, ethereum, sepa, visa, paypal).
   */
  paymentNetwork?: string

  /**
   * Identifier of the underlying payment transaction (e.g. bank reference, onchain transaction hash, or processor-specific ID). Use paymentNetwork to specify the network where applicable.
   */
  transactionId?: string

  /**
   * Optional reference to the activity, project, or organization this funding relates to.
   */
  for?: l.AtUriString

  /**
   * Optional notes or additional context for this funding receipt.
   */
  notes?: string

  /**
   * Timestamp when the payment occurred.
   */
  occurredAt?: l.DatetimeString

  /**
   * Client-declared timestamp when this receipt record was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Records a funding receipt for a payment from one user to another user. It may be recorded by the recipient, by the sender, or by a third party. The sender may remain anonymous. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    from: l.ref<CertifiedDefs.Did>((() => CertifiedDefs.did) as any),
    to: l.string({ maxLength: 2048 }),
    amount: l.string({ maxLength: 50 }),
    currency: l.string({ maxLength: 10 }),
    paymentRail: l.optional(l.string({ maxLength: 50 })),
    paymentNetwork: l.optional(l.string({ maxLength: 50 })),
    transactionId: l.optional(l.string({ maxLength: 256 })),
    for: l.optional(l.string({ format: 'at-uri' })),
    notes: l.optional(l.string({ maxLength: 500 })),
    occurredAt: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
