/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.bumicerts.funding.config'

export { $nsid }

/** Reference to an EVM wallet link record (app.bumicerts.link.evm). */
type EvmLinkRef = {
  $type?: 'app.bumicerts.funding.config#evmLinkRef'

  /**
   * AT-URI of the app.bumicerts.link.evm record.
   */
  uri: l.AtUriString
}

export type { EvmLinkRef }

/** Reference to an EVM wallet link record (app.bumicerts.link.evm). */
const evmLinkRef = l.typedObject<EvmLinkRef>(
  $nsid,
  'evmLinkRef',
  l.object({ uri: l.string({ format: 'at-uri' }) }),
)

export { evmLinkRef }

/** The funding / donations configuration for a given bumicert. */
type Main = {
  $type: 'app.bumicerts.funding.config'

  /**
   * Reference to the wallet link record where funds should be received. Open union to support future wallet types (e.g. Solana, Cosmos).
   */
  receivingWallet: l.$Typed<EvmLinkRef> | l.Unknown$TypedObject

  /**
   * An optional field to set a fundraising goal in USD (e.g. '1000.50').
   */
  goalInUSD?: string

  /**
   * Optional minimum donation amount in USD (e.g. '1.00'). Donations below this amount will be rejected.
   */
  minDonationInUSD?: string

  /**
   * Optional maximum donation amount in USD (e.g. '10000.00'). Donations above this amount will be rejected.
   */
  maxDonationInUSD?: string

  /**
   * An optional field to determine if donations are accepted post the goal reach. Defaults to true (overselling is allowed).
   */
  allowOversell?: boolean

  /**
   * The current status of the listing. Defaults to 'open'.
   */
  status?: 'coming-soon' | 'open' | 'paused' | 'closed' | l.UnknownString

  /**
   * Client-declared timestamp when this record was last updated.
   */
  updatedAt: l.DatetimeString

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** The funding / donations configuration for a given bumicert. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    receivingWallet: l.typedUnion(
      [l.typedRef<EvmLinkRef>((() => evmLinkRef) as any)],
      false,
    ),
    goalInUSD: l.optional(l.string({ maxLength: 50 })),
    minDonationInUSD: l.optional(l.string({ maxLength: 50 })),
    maxDonationInUSD: l.optional(l.string({ maxLength: 50 })),
    allowOversell: l.optional(l.withDefault(l.boolean(), true)),
    status: l.optional(
      l.string<{ knownValues: ['coming-soon', 'open', 'paused', 'closed'] }>(),
    ),
    updatedAt: l.string({ format: 'datetime' }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
