/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.dwc.defs'

export { $nsid }

/** A geographic point with uncertainty, following Darwin Core Location class */
type Geolocation = {
  $type?: 'app.gainforest.dwc.defs#geolocation'

  /**
   * Geographic latitude in decimal degrees (WGS84). Positive values north of the Equator, negative south. Range: -90 to 90.
   */
  decimalLatitude: string

  /**
   * Geographic longitude in decimal degrees (WGS84). Positive values east of the Greenwich Meridian, negative west. Range: -180 to 180.
   */
  decimalLongitude: string

  /**
   * Horizontal distance from the coordinates describing the smallest circle containing the whole location. Zero is not valid.
   */
  coordinateUncertaintyInMeters?: number

  /**
   * The ellipsoid, geodetic datum, or spatial reference system. Recommended: 'EPSG:4326' (WGS84)
   */
  geodeticDatum?: string
}

export type { Geolocation }

/** A geographic point with uncertainty, following Darwin Core Location class */
const geolocation = l.typedObject<Geolocation>(
  $nsid,
  'geolocation',
  l.object({
    decimalLatitude: l.string({ maxGraphemes: 32 }),
    decimalLongitude: l.string({ maxGraphemes: 32 }),
    coordinateUncertaintyInMeters: l.optional(l.integer({ minimum: 1 })),
    geodeticDatum: l.optional(l.string({ maxGraphemes: 64 })),
  }),
)

export { geolocation }

/** A taxonomic identification with provenance metadata */
type TaxonIdentification = {
  $type?: 'app.gainforest.dwc.defs#taxonIdentification'

  /**
   * The full scientific name including authorship and date
   */
  scientificName: string

  /**
   * GBIF backbone taxonomy key for the identified taxon
   */
  gbifTaxonKey?: string

  /**
   * Person(s) who made the identification (pipe-delimited for multiple)
   */
  identifiedBy?: string

  /**
   * ORCID or other persistent identifier for the person(s) who identified (pipe-delimited)
   */
  identifiedByID?: string

  /**
   * Date the identification was made (ISO 8601)
   */
  dateIdentified?: string

  /**
   * Uncertainty qualifier applied to the taxon name (e.g., 'cf. agrestis', 'aff. agrestis')
   */
  identificationQualifier?: string

  /**
   * Notes or comments about the identification
   */
  identificationRemarks?: string
}

export type { TaxonIdentification }

/** A taxonomic identification with provenance metadata */
const taxonIdentification = l.typedObject<TaxonIdentification>(
  $nsid,
  'taxonIdentification',
  l.object({
    scientificName: l.string({ maxGraphemes: 512 }),
    gbifTaxonKey: l.optional(l.string({ maxGraphemes: 64 })),
    identifiedBy: l.optional(l.string({ maxGraphemes: 512 })),
    identifiedByID: l.optional(l.string({ maxGraphemes: 512 })),
    dateIdentified: l.optional(l.string({ maxGraphemes: 64 })),
    identificationQualifier: l.optional(l.string({ maxGraphemes: 256 })),
    identificationRemarks: l.optional(l.string({ maxGraphemes: 2048 })),
  }),
)

export { taxonIdentification }

/** The specific nature of the data record. Controlled vocabulary per Darwin Core. */
type BasisOfRecordEnum =
  | 'HumanObservation'
  | 'MachineObservation'
  | 'PreservedSpecimen'
  | 'LivingSpecimen'
  | 'FossilSpecimen'
  | 'MaterialSample'
  | 'MaterialEntity'
  | 'MaterialCitation'
  | l.UnknownString

export type { BasisOfRecordEnum }

/** The specific nature of the data record. Controlled vocabulary per Darwin Core. */
const basisOfRecordEnum = l.string<{
  maxGraphemes: 64
  knownValues: [
    'HumanObservation',
    'MachineObservation',
    'PreservedSpecimen',
    'LivingSpecimen',
    'FossilSpecimen',
    'MaterialSample',
    'MaterialEntity',
    'MaterialCitation',
  ]
}>({ maxGraphemes: 64 })

export { basisOfRecordEnum }

/** Statement about the presence or absence of a taxon at a location. */
type OccurrenceStatusEnum = 'present' | 'absent' | l.UnknownString

export type { OccurrenceStatusEnum }

/** Statement about the presence or absence of a taxon at a location. */
const occurrenceStatusEnum = l.string<{
  maxGraphemes: 64
  knownValues: ['present', 'absent']
}>({ maxGraphemes: 64 })

export { occurrenceStatusEnum }

/** Dublin Core type vocabulary for the nature of the resource. */
type DublinCoreTypeEnum =
  | 'PhysicalObject'
  | 'StillImage'
  | 'MovingImage'
  | 'Sound'
  | 'Text'
  | 'Event'
  | 'Dataset'
  | l.UnknownString

export type { DublinCoreTypeEnum }

/** Dublin Core type vocabulary for the nature of the resource. */
const dublinCoreTypeEnum = l.string<{
  maxGraphemes: 64
  knownValues: [
    'PhysicalObject',
    'StillImage',
    'MovingImage',
    'Sound',
    'Text',
    'Event',
    'Dataset',
  ]
}>({ maxGraphemes: 64 })

export { dublinCoreTypeEnum }

/** The nomenclatural code under which the scientific name is constructed. */
type NomenclaturalCodeEnum =
  | 'ICZN'
  | 'ICN'
  | 'ICNP'
  | 'ICTV'
  | 'BioCode'
  | l.UnknownString

export type { NomenclaturalCodeEnum }

/** The nomenclatural code under which the scientific name is constructed. */
const nomenclaturalCodeEnum = l.string<{
  maxGraphemes: 64
  knownValues: ['ICZN', 'ICN', 'ICNP', 'ICTV', 'BioCode']
}>({ maxGraphemes: 64 })

export { nomenclaturalCodeEnum }

/** The sex of the biological individual(s) represented in the occurrence. */
type SexEnum = 'male' | 'female' | 'hermaphrodite' | l.UnknownString

export type { SexEnum }

/** The sex of the biological individual(s) represented in the occurrence. */
const sexEnum = l.string<{
  maxGraphemes: 64
  knownValues: ['male', 'female', 'hermaphrodite']
}>({ maxGraphemes: 64 })

export { sexEnum }

/** The taxonomic rank of the most specific name in the scientificName. */
type TaxonRankEnum =
  | 'kingdom'
  | 'phylum'
  | 'class'
  | 'order'
  | 'family'
  | 'subfamily'
  | 'genus'
  | 'subgenus'
  | 'species'
  | 'subspecies'
  | 'variety'
  | 'form'
  | l.UnknownString

export type { TaxonRankEnum }

/** The taxonomic rank of the most specific name in the scientificName. */
const taxonRankEnum = l.string<{
  maxGraphemes: 64
  knownValues: [
    'kingdom',
    'phylum',
    'class',
    'order',
    'family',
    'subfamily',
    'genus',
    'subgenus',
    'species',
    'subspecies',
    'variety',
    'form',
  ]
}>({ maxGraphemes: 64 })

export { taxonRankEnum }
