/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.dwc.event'

export { $nsid }

/** A sampling or collecting event. Multiple dwc.occurrence records can reference the same event via eventRef, sharing location and protocol metadata. */
type Main = {
  $type: 'app.gainforest.dwc.event'

  /**
   * An identifier for the event. Should be globally unique or unique within the dataset.
   */
  eventID: string

  /**
   * An identifier for the broader event that this event is part of (e.g., a survey campaign that contains multiple transects).
   */
  parentEventID?: string

  /**
   * AT-URI reference to the parent app.gainforest.dwc.event record.
   */
  parentEventRef?: l.AtUriString

  /**
   * The date or date range during which the event occurred. ISO 8601 format (e.g., '2024-03-15', '2024-03-15/2024-03-17').
   */
  eventDate: string

  /**
   * The time or time range during which the event occurred. ISO 8601 format (e.g., '06:30:00', '06:30:00/09:00:00').
   */
  eventTime?: string

  /**
   * A category or description of the habitat in which the event occurred (e.g., 'primary tropical rainforest', 'degraded pasture', 'riparian zone').
   */
  habitat?: string

  /**
   * The names of, references to, or descriptions of the methods used during the event (e.g., 'camera trap array', 'line transect distance sampling', 'audio point count 10-min').
   */
  samplingProtocol?: string

  /**
   * A numeric value for a measurement of the size of a sample in the event (e.g., '20', '0.25').
   */
  sampleSizeValue?: string

  /**
   * The unit of measurement for the sampleSizeValue (e.g., 'square meters', 'hectares', 'trap-nights').
   */
  sampleSizeUnit?: string

  /**
   * The amount of effort expended during the event (e.g., '3 person-hours', '14 trap-nights', '2 km transect walked').
   */
  samplingEffort?: string

  /**
   * Notes or a reference to notes taken in the field about the event.
   */
  fieldNotes?: string

  /**
   * Comments or notes about the event.
   */
  eventRemarks?: string

  /**
   * Identifier for the location where the event occurred.
   */
  locationID?: string

  /**
   * Geographic latitude in decimal degrees (WGS84). Range: -90 to 90.
   */
  decimalLatitude?: string

  /**
   * Geographic longitude in decimal degrees (WGS84). Range: -180 to 180.
   */
  decimalLongitude?: string

  /**
   * The spatial reference system. Recommended: 'EPSG:4326'.
   */
  geodeticDatum?: string

  /**
   * Uncertainty radius in meters around the coordinates.
   */
  coordinateUncertaintyInMeters?: number

  /**
   * The name of the country.
   */
  country?: string

  /**
   * ISO 3166-1 alpha-2 country code.
   */
  countryCode?: string

  /**
   * First-level administrative division.
   */
  stateProvince?: string

  /**
   * Second-level administrative division.
   */
  county?: string

  /**
   * Third-level administrative division.
   */
  municipality?: string

  /**
   * Specific locality description.
   */
  locality?: string

  /**
   * Lower limit of elevation range in meters above sea level.
   */
  minimumElevationInMeters?: number

  /**
   * Upper limit of elevation range in meters above sea level.
   */
  maximumElevationInMeters?: number

  /**
   * Comments about the location.
   */
  locationRemarks?: string

  /**
   * Timestamp of record creation in the ATProto PDS.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A sampling or collecting event. Multiple dwc.occurrence records can reference the same event via eventRef, sharing location and protocol metadata. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    eventID: l.string({ maxGraphemes: 256 }),
    parentEventID: l.optional(l.string({ maxGraphemes: 256 })),
    parentEventRef: l.optional(l.string({ format: 'at-uri' })),
    eventDate: l.string({ maxGraphemes: 64 }),
    eventTime: l.optional(l.string({ maxGraphemes: 64 })),
    habitat: l.optional(l.string({ maxGraphemes: 512 })),
    samplingProtocol: l.optional(l.string({ maxGraphemes: 1024 })),
    sampleSizeValue: l.optional(l.string({ maxGraphemes: 64 })),
    sampleSizeUnit: l.optional(l.string({ maxGraphemes: 128 })),
    samplingEffort: l.optional(l.string({ maxGraphemes: 256 })),
    fieldNotes: l.optional(l.string({ maxGraphemes: 10000 })),
    eventRemarks: l.optional(l.string({ maxGraphemes: 5000 })),
    locationID: l.optional(l.string({ maxGraphemes: 256 })),
    decimalLatitude: l.optional(l.string({ maxGraphemes: 32 })),
    decimalLongitude: l.optional(l.string({ maxGraphemes: 32 })),
    geodeticDatum: l.optional(l.string({ maxGraphemes: 64 })),
    coordinateUncertaintyInMeters: l.optional(l.integer({ minimum: 1 })),
    country: l.optional(l.string({ maxGraphemes: 128 })),
    countryCode: l.optional(l.string({ minLength: 2, maxLength: 2 })),
    stateProvince: l.optional(l.string({ maxGraphemes: 256 })),
    county: l.optional(l.string({ maxGraphemes: 256 })),
    municipality: l.optional(l.string({ maxGraphemes: 256 })),
    locality: l.optional(l.string({ maxGraphemes: 1024 })),
    minimumElevationInMeters: l.optional(l.integer()),
    maximumElevationInMeters: l.optional(l.integer()),
    locationRemarks: l.optional(l.string({ maxGraphemes: 2048 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
