/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.dwc.measurement'

export { $nsid }

/** A measurement, fact, characteristic, or assertion about an occurrence. Multiple measurement records can reference the same occurrence, solving the Simple DwC one-measurement-per-record limitation. */
type Main = {
  $type: 'app.gainforest.dwc.measurement'

  /**
   * An identifier for the measurement. Should be unique within the dataset.
   */
  measurementID?: string

  /**
   * AT-URI reference to the app.gainforest.dwc.occurrence record this measurement belongs to.
   */
  occurrenceRef: l.AtUriString

  /**
   * The occurrenceID of the linked occurrence record (for cross-system interoperability).
   */
  occurrenceID?: string

  /**
   * The nature of the measurement, fact, characteristic, or assertion (e.g., 'DBH', 'tree height', 'canopy cover', 'tail length', 'body mass', 'soil pH', 'water temperature').
   */
  measurementType: string

  /**
   * The value of the measurement, fact, characteristic, or assertion (e.g., '45.2', 'present', 'blue').
   */
  measurementValue: string

  /**
   * The units for the measurementValue (e.g., 'cm', 'm', 'kg', 'mm', '%', 'degrees Celsius').
   */
  measurementUnit?: string

  /**
   * The description of the potential error associated with the measurementValue (e.g., '0.5 cm', '5%').
   */
  measurementAccuracy?: string

  /**
   * The description of or reference to the method used to determine the measurement (e.g., 'diameter tape at 1.3m height', 'laser rangefinder', 'Bitterlich method').
   */
  measurementMethod?: string

  /**
   * Person(s) who determined the measurement. Pipe-delimited for multiple.
   */
  measurementDeterminedBy?: string

  /**
   * The date the measurement was made. ISO 8601 format.
   */
  measurementDeterminedDate?: string

  /**
   * Comments or notes accompanying the measurement.
   */
  measurementRemarks?: string

  /**
   * Timestamp of record creation in the ATProto PDS.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A measurement, fact, characteristic, or assertion about an occurrence. Multiple measurement records can reference the same occurrence, solving the Simple DwC one-measurement-per-record limitation. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    measurementID: l.optional(l.string({ maxGraphemes: 256 })),
    occurrenceRef: l.string({ format: 'at-uri' }),
    occurrenceID: l.optional(l.string({ maxGraphemes: 256 })),
    measurementType: l.string({ maxGraphemes: 256 }),
    measurementValue: l.string({ maxGraphemes: 1024 }),
    measurementUnit: l.optional(l.string({ maxGraphemes: 64 })),
    measurementAccuracy: l.optional(l.string({ maxGraphemes: 256 })),
    measurementMethod: l.optional(l.string({ maxGraphemes: 1024 })),
    measurementDeterminedBy: l.optional(l.string({ maxGraphemes: 512 })),
    measurementDeterminedDate: l.optional(l.string({ maxGraphemes: 64 })),
    measurementRemarks: l.optional(l.string({ maxGraphemes: 5000 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
