/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommonDefs from '../common/defs.defs'

const $nsid = 'app.gainforest.dwc.occurrence'

export { $nsid }

/** A biodiversity occurrence record following the Simple Darwin Core standard. Each record represents one occurrence of an organism at a location and time. */
type Main = {
  $type: 'app.gainforest.dwc.occurrence'

  /**
   * A globally unique identifier for the occurrence record. Recommended: a persistent URI (e.g., DOI, LSID, or UUID-based URI).
   */
  occurrenceID?: string

  /**
   * The specific nature of the data record. Must be one of the Darwin Core class names.
   */
  basisOfRecord:
    | 'HumanObservation'
    | 'MachineObservation'
    | 'PreservedSpecimen'
    | 'LivingSpecimen'
    | 'FossilSpecimen'
    | 'MaterialSample'
    | 'MaterialEntity'
    | 'MaterialCitation'

  /**
   * The Dublin Core type class that best describes the resource (dc:type).
   */
  dcType?:
    | 'PhysicalObject'
    | 'StillImage'
    | 'MovingImage'
    | 'Sound'
    | 'Text'
    | 'Event'
    | 'Dataset'

  /**
   * A legal document giving official permission to do something with the record. Recommended: a Creative Commons URI (e.g., 'http://creativecommons.org/licenses/by/4.0/').
   */
  license?: string

  /**
   * Person or organization owning or managing rights over the resource.
   */
  rightsHolder?: string

  /**
   * The name or acronym of the institution having custody of the object(s) or information in the record.
   */
  institutionCode?: string

  /**
   * The name, acronym, or code identifying the collection or dataset from which the record was derived.
   */
  collectionCode?: string

  /**
   * The name identifying the dataset from which the record was derived.
   */
  datasetName?: string

  /**
   * A description of what information is withheld from this record and why (e.g., 'coordinates generalized to protect endangered species').
   */
  informationWithheld?: string

  /**
   * A description of actions taken to make the data less specific or complete (e.g., 'coordinates rounded to nearest 0.1 degree').
   */
  dataGeneralizations?: string

  /**
   * A related resource that is referenced, cited, or otherwise pointed to by the record (URL).
   */
  references?: l.UriString

  /**
   * Person(s) responsible for recording the occurrence in the field. Pipe-delimited for multiple (e.g., 'Jane Smith | John Doe').
   */
  recordedBy?: string

  /**
   * Persistent identifier(s) (e.g., ORCID) of the person(s) who recorded. Pipe-delimited for multiple.
   */
  recordedByID?: string

  /**
   * The number of individuals present at the time of the occurrence.
   */
  individualCount?: number

  /**
   * A number or enumeration value for the quantity of organisms (e.g., '27', '12.5', 'many').
   */
  organismQuantity?: string

  /**
   * The type of quantification system used for organismQuantity (e.g., 'individuals', '% biomass', 'stems/ha').
   */
  organismQuantityType?: string

  /**
   * The sex of the biological individual(s).
   */
  sex?: 'male' | 'female' | 'hermaphrodite'

  /**
   * The age class or life stage at the time of occurrence (e.g., 'adult', 'juvenile', 'larva', 'seedling', 'sapling').
   */
  lifeStage?: string

  /**
   * The reproductive condition at the time of occurrence (e.g., 'flowering', 'fruiting', 'budding', 'pregnant').
   */
  reproductiveCondition?: string

  /**
   * The behavior shown by the subject at the time of occurrence (e.g., 'foraging', 'nesting', 'roosting').
   */
  behavior?: string

  /**
   * Statement about the presence or absence of a taxon at a location.
   */
  occurrenceStatus?: 'present' | 'absent'

  /**
   * Comments or notes about the occurrence.
   */
  occurrenceRemarks?: string

  /**
   * Identifiers (URIs) of media associated with the occurrence. Pipe-delimited for multiple.
   */
  associatedMedia?: string

  /**
   * Identifiers (URIs) of literature associated with the occurrence. Pipe-delimited for multiple.
   */
  associatedReferences?: string

  /**
   * Identifiers (URIs) of genetic sequence information associated with the occurrence. Pipe-delimited for multiple.
   */
  associatedSequences?: string

  /**
   * Identifiers of other occurrences associated with this one (e.g., parasite-host). Pipe-delimited.
   */
  associatedOccurrences?: string

  /**
   * Identifier for the sampling event. Can be used to group occurrences from the same event.
   */
  eventID?: string

  /**
   * AT-URI reference to an app.gainforest.dwc.event record (for star-schema linkage).
   */
  eventRef?: l.AtUriString

  /**
   * The date or date-time (or interval) during which the occurrence was recorded. ISO 8601 format (e.g., '2024-03-15', '2024-03-15T10:30:00Z', '2024-03/2024-06').
   */
  eventDate: string

  /**
   * The time of the event. ISO 8601 format (e.g., '14:30:00', '14:30:00+02:00').
   */
  eventTime?: string

  /**
   * A description of the habitat in which the event occurred (e.g., 'tropical rainforest', 'mangrove swamp', 'montane cloud forest').
   */
  habitat?: string

  /**
   * The method or protocol used during the event (e.g., 'camera trap', 'point count', 'mist net', '20m x 20m plot survey', 'acoustic monitoring').
   */
  samplingProtocol?: string

  /**
   * The amount of effort expended during the event (e.g., '2 trap-nights', '30 minutes', '10 km transect').
   */
  samplingEffort?: string

  /**
   * Notes or reference to notes taken in the field about the event.
   */
  fieldNotes?: string

  /**
   * Identifier for the location (e.g., a reference to a named site).
   */
  locationID?: string

  /**
   * Geographic latitude in decimal degrees (WGS84). Positive values are north of the Equator. Range: -90 to 90.
   */
  decimalLatitude?: string

  /**
   * Geographic longitude in decimal degrees (WGS84). Positive values are east of the Greenwich Meridian. Range: -180 to 180.
   */
  decimalLongitude?: string

  /**
   * The spatial reference system for the coordinates. Recommended: 'EPSG:4326' (WGS84).
   */
  geodeticDatum?: string

  /**
   * Horizontal distance (meters) from the given coordinates describing the smallest circle containing the whole location.
   */
  coordinateUncertaintyInMeters?: number

  /**
   * The name of the country or major administrative unit.
   */
  country?: string

  /**
   * The standard code for the country (ISO 3166-1 alpha-2).
   */
  countryCode?: string

  /**
   * The name of the next smaller administrative region than country.
   */
  stateProvince?: string

  /**
   * The full, unabbreviated name of the next smaller administrative region than stateProvince.
   */
  county?: string

  /**
   * The full, unabbreviated name of the next smaller administrative region than county.
   */
  municipality?: string

  /**
   * The specific description of the place (e.g., '500m upstream of bridge on Rio Pará').
   */
  locality?: string

  /**
   * The original textual description of the place as provided by the recorder.
   */
  verbatimLocality?: string

  /**
   * The lower limit of the range of elevation (in meters above sea level).
   */
  minimumElevationInMeters?: number

  /**
   * The upper limit of the range of elevation (in meters above sea level).
   */
  maximumElevationInMeters?: number

  /**
   * The lesser depth of a range of depth below the local surface (in meters).
   */
  minimumDepthInMeters?: number

  /**
   * The greater depth of a range of depth below the local surface (in meters).
   */
  maximumDepthInMeters?: number

  /**
   * Comments about the location.
   */
  locationRemarks?: string

  /**
   * GBIF backbone taxonomy key for the identified taxon. Retained for backward compatibility with existing GainForest workflows.
   */
  gbifTaxonKey?: string

  /**
   * The full scientific name, with authorship and date if known (e.g., 'Centropyge flavicauda Fraser-Brunner 1933').
   */
  scientificName: string

  /**
   * The authorship information for the scientific name (e.g., 'Fraser-Brunner 1933').
   */
  scientificNameAuthorship?: string

  /**
   * The full scientific name of the kingdom (e.g., 'Animalia', 'Plantae', 'Fungi').
   */
  kingdom?: string

  /**
   * The full scientific name of the phylum or division.
   */
  phylum?: string

  /**
   * The full scientific name of the class.
   */
  class?: string

  /**
   * The full scientific name of the order.
   */
  order?: string

  /**
   * The full scientific name of the family.
   */
  family?: string

  /**
   * The full scientific name of the genus.
   */
  genus?: string

  /**
   * The name of the species epithet of the scientificName.
   */
  specificEpithet?: string

  /**
   * The name of the lowest or terminal infraspecific epithet.
   */
  infraspecificEpithet?: string

  /**
   * The taxonomic rank of the most specific name in scientificName.
   */
  taxonRank?:
    | 'kingdom'
    | 'phylum'
    | 'class'
    | 'order'
    | 'family'
    | 'subfamily'
    | 'genus'
    | 'subgenus'
    | 'species'
    | 'subspecies'
    | 'variety'
    | 'form'

  /**
   * A common or vernacular name for the taxon.
   */
  vernacularName?: string

  /**
   * The status of the use of the scientificName (e.g., 'accepted', 'synonym', 'doubtful').
   */
  taxonomicStatus?: string

  /**
   * The nomenclatural code under which the scientificName is constructed.
   */
  nomenclaturalCode?: 'ICZN' | 'ICN' | 'ICNP' | 'ICTV' | 'BioCode'

  /**
   * A complete list of taxa names terminating at the rank immediately superior to the taxon. Pipe-delimited (e.g., 'Animalia|Chordata|Mammalia|Rodentia|Ctenomyidae|Ctenomys').
   */
  higherClassification?: string

  /**
   * Person(s) who assigned the taxon to the occurrence. Pipe-delimited for multiple.
   */
  identifiedBy?: string

  /**
   * Persistent identifier(s) (e.g., ORCID) of the person(s) who identified. Pipe-delimited.
   */
  identifiedByID?: string

  /**
   * The date on which the identification was made. ISO 8601 format.
   */
  dateIdentified?: string

  /**
   * A brief phrase or standard term qualifying the identification (e.g., 'cf. agrestis', 'aff. agrestis').
   */
  identificationQualifier?: string

  /**
   * Comments or notes about the identification.
   */
  identificationRemarks?: string

  /**
   * Previous assignments of names to the occurrence. Pipe-delimited.
   */
  previousIdentifications?: string

  /**
   * Additional structured data as a valid JSON string (per Simple DwC Section 7.1). Example: '{"iucnStatus":"vulnerable","canopyCover":"85%"}'. Should be flattened to a single line with no non-printing characters.
   */
  dynamicProperties?: string

  /**
   * Image evidence (photo, camera trap, drone still, scanned specimen, etc.).
   */
  imageEvidence?: CommonDefs.Image

  /**
   * Audio evidence (bioacoustics, soundscape, species call, field recording, etc.).
   */
  audioEvidence?: CommonDefs.Audio

  /**
   * Video evidence (camera trap, drone footage, underwater video, behavioral observation, etc.).
   */
  videoEvidence?: CommonDefs.Video

  /**
   * Spectrogram image showing frequency analysis of audio recording.
   */
  spectrogramEvidence?: CommonDefs.Spectrogram

  /**
   * Timestamp of record creation in the ATProto PDS.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A biodiversity occurrence record following the Simple Darwin Core standard. Each record represents one occurrence of an organism at a location and time. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    occurrenceID: l.optional(l.string({ maxGraphemes: 256 })),
    basisOfRecord: l.enum([
      'HumanObservation',
      'MachineObservation',
      'PreservedSpecimen',
      'LivingSpecimen',
      'FossilSpecimen',
      'MaterialSample',
      'MaterialEntity',
      'MaterialCitation',
    ]),
    dcType: l.optional(
      l.enum([
        'PhysicalObject',
        'StillImage',
        'MovingImage',
        'Sound',
        'Text',
        'Event',
        'Dataset',
      ]),
    ),
    license: l.optional(l.string({ maxGraphemes: 512 })),
    rightsHolder: l.optional(l.string({ maxGraphemes: 256 })),
    institutionCode: l.optional(l.string({ maxGraphemes: 256 })),
    collectionCode: l.optional(l.string({ maxGraphemes: 256 })),
    datasetName: l.optional(l.string({ maxGraphemes: 256 })),
    informationWithheld: l.optional(l.string({ maxGraphemes: 1024 })),
    dataGeneralizations: l.optional(l.string({ maxGraphemes: 1024 })),
    references: l.optional(l.string({ format: 'uri' })),
    recordedBy: l.optional(l.string({ maxGraphemes: 512 })),
    recordedByID: l.optional(l.string({ maxGraphemes: 512 })),
    individualCount: l.optional(l.integer({ minimum: 0 })),
    organismQuantity: l.optional(l.string({ maxGraphemes: 64 })),
    organismQuantityType: l.optional(l.string({ maxGraphemes: 128 })),
    sex: l.optional(l.enum(['male', 'female', 'hermaphrodite'])),
    lifeStage: l.optional(l.string({ maxGraphemes: 128 })),
    reproductiveCondition: l.optional(l.string({ maxGraphemes: 128 })),
    behavior: l.optional(l.string({ maxGraphemes: 256 })),
    occurrenceStatus: l.optional(l.enum(['present', 'absent'])),
    occurrenceRemarks: l.optional(l.string({ maxGraphemes: 5000 })),
    associatedMedia: l.optional(l.string({ maxGraphemes: 2048 })),
    associatedReferences: l.optional(l.string({ maxGraphemes: 2048 })),
    associatedSequences: l.optional(l.string({ maxGraphemes: 2048 })),
    associatedOccurrences: l.optional(l.string({ maxGraphemes: 2048 })),
    eventID: l.optional(l.string({ maxGraphemes: 256 })),
    eventRef: l.optional(l.string({ format: 'at-uri' })),
    eventDate: l.string({ maxGraphemes: 64 }),
    eventTime: l.optional(l.string({ maxGraphemes: 64 })),
    habitat: l.optional(l.string({ maxGraphemes: 512 })),
    samplingProtocol: l.optional(l.string({ maxGraphemes: 1024 })),
    samplingEffort: l.optional(l.string({ maxGraphemes: 256 })),
    fieldNotes: l.optional(l.string({ maxGraphemes: 10000 })),
    locationID: l.optional(l.string({ maxGraphemes: 256 })),
    decimalLatitude: l.optional(l.string({ maxGraphemes: 32 })),
    decimalLongitude: l.optional(l.string({ maxGraphemes: 32 })),
    geodeticDatum: l.optional(l.string({ maxGraphemes: 64 })),
    coordinateUncertaintyInMeters: l.optional(l.integer({ minimum: 1 })),
    country: l.optional(l.string({ maxGraphemes: 128 })),
    countryCode: l.optional(l.string({ minLength: 2, maxLength: 2 })),
    stateProvince: l.optional(l.string({ maxGraphemes: 256 })),
    county: l.optional(l.string({ maxGraphemes: 256 })),
    municipality: l.optional(l.string({ maxGraphemes: 256 })),
    locality: l.optional(l.string({ maxGraphemes: 1024 })),
    verbatimLocality: l.optional(l.string({ maxGraphemes: 1024 })),
    minimumElevationInMeters: l.optional(l.integer()),
    maximumElevationInMeters: l.optional(l.integer()),
    minimumDepthInMeters: l.optional(l.integer({ minimum: 0 })),
    maximumDepthInMeters: l.optional(l.integer({ minimum: 0 })),
    locationRemarks: l.optional(l.string({ maxGraphemes: 2048 })),
    gbifTaxonKey: l.optional(l.string({ maxGraphemes: 64 })),
    scientificName: l.string({ maxGraphemes: 512 }),
    scientificNameAuthorship: l.optional(l.string({ maxGraphemes: 256 })),
    kingdom: l.optional(l.string({ maxGraphemes: 128 })),
    phylum: l.optional(l.string({ maxGraphemes: 128 })),
    class: l.optional(l.string({ maxGraphemes: 128 })),
    order: l.optional(l.string({ maxGraphemes: 128 })),
    family: l.optional(l.string({ maxGraphemes: 128 })),
    genus: l.optional(l.string({ maxGraphemes: 128 })),
    specificEpithet: l.optional(l.string({ maxGraphemes: 128 })),
    infraspecificEpithet: l.optional(l.string({ maxGraphemes: 128 })),
    taxonRank: l.optional(
      l.enum([
        'kingdom',
        'phylum',
        'class',
        'order',
        'family',
        'subfamily',
        'genus',
        'subgenus',
        'species',
        'subspecies',
        'variety',
        'form',
      ]),
    ),
    vernacularName: l.optional(l.string({ maxGraphemes: 256 })),
    taxonomicStatus: l.optional(l.string({ maxGraphemes: 64 })),
    nomenclaturalCode: l.optional(
      l.enum(['ICZN', 'ICN', 'ICNP', 'ICTV', 'BioCode']),
    ),
    higherClassification: l.optional(l.string({ maxGraphemes: 1024 })),
    identifiedBy: l.optional(l.string({ maxGraphemes: 512 })),
    identifiedByID: l.optional(l.string({ maxGraphemes: 512 })),
    dateIdentified: l.optional(l.string({ maxGraphemes: 64 })),
    identificationQualifier: l.optional(l.string({ maxGraphemes: 256 })),
    identificationRemarks: l.optional(l.string({ maxGraphemes: 2048 })),
    previousIdentifications: l.optional(l.string({ maxGraphemes: 2048 })),
    dynamicProperties: l.optional(l.string({ maxGraphemes: 10000 })),
    imageEvidence: l.optional(
      l.ref<CommonDefs.Image>((() => CommonDefs.image) as any),
    ),
    audioEvidence: l.optional(
      l.ref<CommonDefs.Audio>((() => CommonDefs.audio) as any),
    ),
    videoEvidence: l.optional(
      l.ref<CommonDefs.Video>((() => CommonDefs.video) as any),
    ),
    spectrogramEvidence: l.optional(
      l.ref<CommonDefs.Spectrogram>((() => CommonDefs.spectrogram) as any),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
