/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BadgeDefinition from './definition.defs'
import * as CertifiedDefs from '../defs.defs'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'

const $nsid = 'app.certified.badge.award'

export { $nsid }

/** Records a badge award to a user, project, or activity claim. */
type Main = {
  $type: 'app.certified.badge.award'

  /**
   * Reference to the badge definition for this award.
   */
  badge: BadgeDefinition.Main

  /**
   * Entity the badge award is for (either an account DID or any specific AT Protocol record), e.g. a user, a project, or a specific activity claim.
   */
  subject:
    | l.$Typed<CertifiedDefs.Did>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject

  /**
   * Optional statement explaining the reason for this badge award.
   */
  note?: string

  /**
   * Optional URL the badge award links to.
   */
  url?: l.UriString

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Records a badge award to a user, project, or activity claim. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    badge: l.ref<BadgeDefinition.Main>((() => BadgeDefinition.main) as any),
    subject: l.typedUnion(
      [
        l.typedRef<CertifiedDefs.Did>((() => CertifiedDefs.did) as any),
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
      ],
      false,
    ),
    note: l.optional(l.string({ maxLength: 500 })),
    url: l.optional(l.string({ format: 'uri', maxLength: 2048 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
