/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CertifiedDefs from '../defs.defs'

const $nsid = 'app.certified.badge.definition'

export { $nsid }

/** Defines a badge that can be awarded via badge award records to users, projects, or activity claims. */
type Main = {
  $type: 'app.certified.badge.definition'

  /**
   * Category of the badge (e.g. endorsement, participation, affiliation).
   */
  badgeType: string

  /**
   * Human-readable title of the badge.
   */
  title: string

  /**
   * Icon representing the badge, stored as a blob for compact visual display.
   */
  icon: l.BlobRef

  /**
   * Optional short statement describing what the badge represents.
   */
  description?: string

  /**
   * Optional allowlist of DIDs allowed to issue this badge. If omitted, anyone may issue it.
   */
  allowedIssuers?: CertifiedDefs.Did[]

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Defines a badge that can be awarded via badge award records to users, projects, or activity claims. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    badgeType: l.string({ maxLength: 100 }),
    title: l.string({ maxLength: 256 }),
    icon: l.blob({
      accept: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'],
      maxSize: 1048576,
      allowLegacy: false,
    }),
    description: l.optional(l.string({ maxLength: 5000, maxGraphemes: 500 })),
    allowedIssuers: l.optional(
      l.array(l.ref<CertifiedDefs.Did>((() => CertifiedDefs.did) as any), {
        maxLength: 100,
      }),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
