/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BadgeAward from './award.defs'

const $nsid = 'app.certified.badge.response'

export { $nsid }

/** Recipient response to a badge award. */
type Main = {
  $type: 'app.certified.badge.response'

  /**
   * Reference to the badge award.
   */
  badgeAward: BadgeAward.Main

  /**
   * The recipient’s response for the badge (accepted or rejected).
   */
  response: 'accepted' | 'rejected' | l.UnknownString

  /**
   * Optional relative weight for accepted badges, assigned by the recipient.
   */
  weight?: string

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Recipient response to a badge award. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    badgeAward: l.ref<BadgeAward.Main>((() => BadgeAward.main) as any),
    response: l.string<{ knownValues: ['accepted', 'rejected'] }>(),
    weight: l.optional(l.string({ maxLength: 50 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
