/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ReviewDefs from './defs.defs'

const $nsid = 'org.impactindexer.review.comment'

export { $nsid }

/** A text comment on a subject. */
type Main = {
  $type: 'org.impactindexer.review.comment'

  /**
   * The subject being commented on.
   */
  subject: ReviewDefs.SubjectRef

  /**
   * The comment text.
   */
  text: string

  /**
   * Optional AT-URI of another comment this is replying to, enabling threaded discussions.
   */
  replyTo?: l.AtUriString

  /**
   * Timestamp when the comment was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A text comment on a subject. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subject: l.ref<ReviewDefs.SubjectRef>((() => ReviewDefs.subjectRef) as any),
    text: l.string({ maxLength: 20480, maxGraphemes: 6000 }),
    replyTo: l.optional(l.string({ format: 'at-uri' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
