/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.impactindexer.review.defs'

export { $nsid }

/** The type of subject being reviewed. */
type SubjectType = 'record' | 'user' | 'pds' | 'lexicon' | l.UnknownString

export type { SubjectType }

/** The type of subject being reviewed. */
const subjectType = l.string<{
  maxLength: 32
  knownValues: ['record', 'user', 'pds', 'lexicon']
}>({ maxLength: 32 })

export { subjectType }

/** Reference to the subject being reviewed. */
type SubjectRef = {
  $type?: 'org.impactindexer.review.defs#subjectRef'

  /**
   * The subject identifier. For records: AT-URI (at://did/collection/rkey). For users: DID (did:plc:xxx). For PDSes: hostname (example.com). For lexicons: NSID (app.bsky.feed.post).
   */
  uri: string

  /**
   * The type of subject.
   */
  type: SubjectType

  /**
   * Optional CID for record subjects to pin to a specific version.
   */
  cid?: string
}

export type { SubjectRef }

/** Reference to the subject being reviewed. */
const subjectRef = l.typedObject<SubjectRef>(
  $nsid,
  'subjectRef',
  l.object({
    uri: l.string({ maxLength: 8192 }),
    type: l.ref<SubjectType>((() => subjectType) as any),
    cid: l.optional(l.string({ maxLength: 128 })),
  }),
)

export { subjectRef }
