/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ReviewDefs from './defs.defs'

const $nsid = 'org.impactindexer.review.like'

export { $nsid }

/** A like on a subject. Create to like, delete to remove like. */
type Main = {
  $type: 'org.impactindexer.review.like'

  /**
   * The subject being liked.
   */
  subject: ReviewDefs.SubjectRef

  /**
   * Timestamp when the like was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A like on a subject. Create to like, delete to remove like. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subject: l.ref<ReviewDefs.SubjectRef>((() => ReviewDefs.subjectRef) as any),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
