/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as PagesLinearDocument from '../../pub/leaflet/pages/linearDocument.defs'
import * as HypercertsDefs from './defs.defs'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs'

const $nsid = 'org.hypercerts.collection'

export { $nsid }

/** A collection/group of items (activities and/or other collections). Collections support recursive nesting. */
type Main = {
  $type: 'org.hypercerts.collection'

  /**
   * The type of this collection. Possible fields can be 'favorites', 'project', or any other type of collection.
   */
  type?: string

  /**
   * Display name for this collection (e.g. 'Q1 2025 Impact Projects')
   */
  title: string

  /**
   * Short summary of this collection, suitable for previews and list views
   */
  shortDescription?: string

  /**
   * Rich-text description, represented as a Leaflet linear document.
   */
  description?: PagesLinearDocument.Main

  /**
   * The collection's avatar/profile image as a URI or image blob.
   */
  avatar?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Larger horizontal image to display behind the collection view.
   */
  banner?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.LargeImage>
    | l.Unknown$TypedObject

  /**
   * Array of items in this collection with optional weights.
   */
  items?: Item[]

  /**
   * A strong reference to the location where this collection's activities were performed. The record referenced must conform with the lexicon app.certified.location.
   */
  location?: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A collection/group of items (activities and/or other collections). Collections support recursive nesting. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    type: l.optional(l.string({ maxLength: 64 })),
    title: l.string({ maxLength: 800, maxGraphemes: 80 }),
    shortDescription: l.optional(
      l.string({ maxLength: 3000, maxGraphemes: 300 }),
    ),
    description: l.optional(
      l.ref<PagesLinearDocument.Main>((() => PagesLinearDocument.main) as any),
    ),
    avatar: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    banner: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.LargeImage>(
            (() => HypercertsDefs.largeImage) as any,
          ),
        ],
        false,
      ),
    ),
    items: l.optional(
      l.array(l.ref<Item>((() => item) as any), { maxLength: 1000 }),
    ),
    location: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Item = {
  $type?: 'org.hypercerts.collection#item'

  /**
   * Strong reference to an item in this collection. Items can be activities (org.hypercerts.claim.activity) and/or other collections (org.hypercerts.collection).
   */
  itemIdentifier: RepoStrongRef.Main

  /**
   * Optional weight for this item (positive numeric value stored as string). Weights do not need to sum to a specific total; normalization can be performed by the consuming application as needed.
   */
  itemWeight?: string
}

export type { Item }

const item = l.typedObject<Item>(
  $nsid,
  'item',
  l.object({
    itemIdentifier: l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    itemWeight: l.optional(l.string({ maxLength: 100 })),
  }),
)

export { item }
