/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.hypercerts.defs'

export { $nsid }

/** Object containing a URI to external data */
type Uri = {
  $type?: 'org.hypercerts.defs#uri'

  /**
   * URI to external data
   */
  uri: l.UriString
}

export type { Uri }

/** Object containing a URI to external data */
const uri = l.typedObject<Uri>(
  $nsid,
  'uri',
  l.object({ uri: l.string({ format: 'uri' }) }),
)

export { uri }

/** Object containing a blob to external data */
type SmallBlob = {
  $type?: 'org.hypercerts.defs#smallBlob'

  /**
   * Blob to external data (up to 10MB)
   */
  blob: l.BlobRef
}

export type { SmallBlob }

/** Object containing a blob to external data */
const smallBlob = l.typedObject<SmallBlob>(
  $nsid,
  'smallBlob',
  l.object({
    blob: l.blob({ accept: ['*/*'], maxSize: 10485760, allowLegacy: false }),
  }),
)

export { smallBlob }

/** Object containing a blob to external data */
type LargeBlob = {
  $type?: 'org.hypercerts.defs#largeBlob'

  /**
   * Blob to external data (up to 100MB)
   */
  blob: l.BlobRef
}

export type { LargeBlob }

/** Object containing a blob to external data */
const largeBlob = l.typedObject<LargeBlob>(
  $nsid,
  'largeBlob',
  l.object({
    blob: l.blob({ accept: ['*/*'], maxSize: 104857600, allowLegacy: false }),
  }),
)

export { largeBlob }

/** Object containing a small image */
type SmallImage = {
  $type?: 'org.hypercerts.defs#smallImage'

  /**
   * Image (up to 5MB)
   */
  image: l.BlobRef
}

export type { SmallImage }

/** Object containing a small image */
const smallImage = l.typedObject<SmallImage>(
  $nsid,
  'smallImage',
  l.object({
    image: l.blob({
      accept: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
      maxSize: 5242880,
      allowLegacy: false,
    }),
  }),
)

export { smallImage }

/** Object containing a small video */
type SmallVideo = {
  $type?: 'org.hypercerts.defs#smallVideo'

  /**
   * Video (up to 20MB)
   */
  video: l.BlobRef
}

export type { SmallVideo }

/** Object containing a small video */
const smallVideo = l.typedObject<SmallVideo>(
  $nsid,
  'smallVideo',
  l.object({
    video: l.blob({
      accept: ['video/mp4', 'video/webm'],
      maxSize: 20971520,
      allowLegacy: false,
    }),
  }),
)

export { smallVideo }

/** Object containing a large image */
type LargeImage = {
  $type?: 'org.hypercerts.defs#largeImage'

  /**
   * Image (up to 10MB)
   */
  image: l.BlobRef
}

export type { LargeImage }

/** Object containing a large image */
const largeImage = l.typedObject<LargeImage>(
  $nsid,
  'largeImage',
  l.object({
    image: l.blob({
      accept: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
      maxSize: 10485760,
      allowLegacy: false,
    }),
  }),
)

export { largeImage }
