/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommonDefs from '../../common/defs.defs'

const $nsid = 'app.gainforest.organization.recordings.audio'

export { $nsid }

/** A declaration of an audio recording */
type Main = {
  $type: 'app.gainforest.organization.recordings.audio'

  /**
   * A short name for the audio recording
   */
  name: string

  /**
   * A description of the audio recording
   */
  description?: CommonDefs.Richtext

  /**
   * The blob of the audio recording
   */
  blob: CommonDefs.Audio

  /**
   * The metadata of the audio recording
   */
  metadata: Metadata

  /**
   * The date and time of the creation of the record
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A declaration of an audio recording */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string(),
    description: l.optional(
      l.ref<CommonDefs.Richtext>((() => CommonDefs.richtext) as any),
    ),
    blob: l.ref<CommonDefs.Audio>((() => CommonDefs.audio) as any),
    metadata: l.ref<Metadata>((() => metadata) as any),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Metadata = {
  $type?: 'app.gainforest.organization.recordings.audio#metadata'

  /**
   * The codec of the audio recording
   */
  codec: string

  /**
   * The number of channels of the audio recording
   */
  channels: number

  /**
   * The duration of the audio recording in seconds
   */
  duration: string

  /**
   * The date and time of the recording
   */
  recordedAt: l.DatetimeString

  /**
   * The sample rate of the audio recording
   */
  sampleRate: number

  /**
   * The coordinates at which the audio was recorded in the format 'latitude,longitude' OR 'latitude,longitude,altitude'
   */
  coordinates?: string
}

export type { Metadata }

const metadata = l.typedObject<Metadata>(
  $nsid,
  'metadata',
  l.object({
    codec: l.string(),
    channels: l.integer(),
    duration: l.string(),
    recordedAt: l.string({ format: 'datetime' }),
    sampleRate: l.integer(),
    coordinates: l.optional(l.string()),
  }),
)

export { metadata }
