/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'

const $nsid = 'app.certified.actor.organization'

export { $nsid }

/** Extended metadata for an organization actor. Complements the base actor profile with organization-specific fields like legal structure and reference links. */
type Main = {
  $type: 'app.certified.actor.organization'

  /**
   * Legal or operational structures of the organization (e.g. 'nonprofit', 'ngo', 'government', 'social-enterprise', 'cooperative').
   */
  organizationType?: string[]

  /**
   * Additional reference URLs (social media profiles, contact pages, donation links, etc.) with a display label for each URL.
   */
  urls?: UrlItem[]

  /**
   * A strong reference to the location where the organization is based. The record referenced must conform with the lexicon app.certified.location.
   */
  location?: RepoStrongRef.Main

  /**
   * When the organization was established. Stored as datetime per ATProto conventions (no date-only format exists). Clients should use midnight UTC (e.g., '2005-01-01T00:00:00.000Z'); consumers should treat only the date portion as canonical.
   */
  foundedDate?: l.DatetimeString

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Extended metadata for an organization actor. Complements the base actor profile with organization-specific fields like legal structure and reference links. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    organizationType: l.optional(
      l.array(l.string({ maxLength: 128, maxGraphemes: 100 }), {
        maxLength: 10,
      }),
    ),
    urls: l.optional(l.array(l.ref<UrlItem>((() => urlItem) as any))),
    location: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    foundedDate: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A labeled URL reference. */
type UrlItem = {
  $type?: 'app.certified.actor.organization#urlItem'

  /**
   * The URL.
   */
  url: l.UriString

  /**
   * Optional human-readable label for this URL (e.g. 'Support page', 'Donation page').
   */
  label?: string
}

export type { UrlItem }

/** A labeled URL reference. */
const urlItem = l.typedObject<UrlItem>(
  $nsid,
  'urlItem',
  l.object({
    url: l.string({ format: 'uri', maxLength: 10000, maxGraphemes: 2048 }),
    label: l.optional(l.string({ maxLength: 640, maxGraphemes: 64 })),
  }),
)

export { urlItem }
