/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../../../org/hypercerts/defs.defs'

const $nsid = 'app.certified.actor.profile'

export { $nsid }

/** A declaration of a Certified account profile. */
type Main = {
  $type: 'app.certified.actor.profile'

  /**
   * Display name for the account
   */
  displayName?: string

  /**
   * Free-form profile description text.
   */
  description?: string

  /**
   * Free-form pronouns text.
   */
  pronouns?: string

  /**
   * Account website URL
   */
  website?: l.UriString

  /**
   * Small image to be displayed next to posts from account. AKA, 'profile picture'
   */
  avatar?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Larger horizontal image to display behind profile view.
   */
  banner?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.LargeImage>
    | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A declaration of a Certified account profile. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    description: l.optional(l.string({ maxGraphemes: 256, maxLength: 2560 })),
    pronouns: l.optional(l.string({ maxGraphemes: 20, maxLength: 200 })),
    website: l.optional(l.string({ format: 'uri' })),
    avatar: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    banner: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.LargeImage>(
            (() => HypercertsDefs.largeImage) as any,
          ),
        ],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
