/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.certified.defs'

export { $nsid }

/** A Decentralized Identifier (DID) string. */
type Did = {
  $type?: 'app.certified.defs#did'

  /**
   * The DID string value.
   */
  did: l.DidString
}

export type { Did }

/** A Decentralized Identifier (DID) string. */
const did = l.typedObject<Did>(
  $nsid,
  'did',
  l.object({ did: l.string({ format: 'did', maxLength: 256 }) }),
)

export { did }
