/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../../org/hypercerts/defs.defs'

const $nsid = 'app.certified.location'

export { $nsid }

/** A location reference */
type Main = {
  $type: 'app.certified.location'

  /**
   * The version of the Location Protocol
   */
  lpVersion: string

  /**
   * The Spatial Reference System URI (e.g., http://www.opengis.net/def/crs/OGC/1.3/CRS84) that defines the coordinate system.
   */
  srs: l.UriString

  /**
   * An identifier for the format of the location data (e.g., coordinate-decimal, geojson-point). See the Location Protocol spec for the full registry: https://spec.decentralizedgeo.org/specification/location-types/#location-type-registry
   */
  locationType:
    | 'coordinate-decimal'
    | 'geojson-point'
    | 'geojson'
    | 'h3'
    | 'geohash'
    | 'wkt'
    | 'address'
    | 'scaledCoordinates'
    | l.UnknownString

  /**
   * The location of where the work was performed as a URI, blob, or inline string.
   */
  location:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallBlob>
    | l.$Typed<String$0>
    | l.Unknown$TypedObject

  /**
   * Human-readable name for this location (e.g. 'Golden Gate Park', 'San Francisco Bay Area')
   */
  name?: string

  /**
   * Additional context about this location, such as its significance to the work or specific boundaries
   */
  description?: string

  /**
   * Client-declared timestamp when this record was originally created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A location reference */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    lpVersion: l.string({ maxLength: 10 }),
    srs: l.string({ format: 'uri', maxLength: 100 }),
    locationType: l.string<{
      knownValues: [
        'coordinate-decimal',
        'geojson-point',
        'geojson',
        'h3',
        'geohash',
        'wkt',
        'address',
        'scaledCoordinates',
      ]
      maxLength: 20
    }>({ maxLength: 20 }),
    location: l.typedUnion(
      [
        l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
        l.typedRef<HypercertsDefs.SmallBlob>(
          (() => HypercertsDefs.smallBlob) as any,
        ),
        l.typedRef<String$0>((() => string$0) as any),
      ],
      false,
    ),
    name: l.optional(l.string({ maxLength: 1000, maxGraphemes: 100 })),
    description: l.optional(l.string({ maxLength: 2000, maxGraphemes: 500 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A location represented as a string, e.g. coordinates or a small GeoJSON string. */
type String$0 = {
  $type?: 'app.certified.location#string'

  /**
   * The location string value
   */
  string: string
}

export type { String$0 as String }

/** A location represented as a string, e.g. coordinates or a small GeoJSON string. */
const string$0 = l.typedObject<String$0>(
  $nsid,
  'string',
  l.object({ string: l.string({ maxLength: 10000, maxGraphemes: 1000 }) }),
)

export { string$0 as string }
