/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../../../../org/hypercerts/defs.defs'

const $nsid = 'app.gainforest.organization.observations.measuredTreesCluster'

export { $nsid }

/** A declaration of a measured trees cluster for an organization */
type Main = {
  $type: 'app.gainforest.organization.observations.measuredTreesCluster'

  /**
   * A blob pointing to a shapefile of the measured trees cluster
   */
  shapefile: HypercertsDefs.SmallBlob

  /**
   * The date and time of the creation of the record
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A declaration of a measured trees cluster for an organization */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    shapefile: l.ref<HypercertsDefs.SmallBlob>(
      (() => HypercertsDefs.smallBlob) as any,
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
