/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.evaluator.defs'

export { $nsid }

/** Reference to a target record that is being evaluated. */
type SubjectRef = {
  $type?: 'app.gainforest.evaluator.defs#subjectRef'

  /**
   * AT-URI of the target record.
   */
  uri: l.AtUriString

  /**
   * CID pinning the exact version of the target record.
   */
  cid?: l.CidString
}

export type { SubjectRef }

/** Reference to a target record that is being evaluated. */
const subjectRef = l.typedObject<SubjectRef>(
  $nsid,
  'subjectRef',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
  }),
)

export { subjectRef }

/** Provenance metadata describing the method used to produce an evaluation. */
type MethodInfo = {
  $type?: 'app.gainforest.evaluator.defs#methodInfo'

  /**
   * Human-readable name of the method or model (e.g., 'GainForest BioClassifier').
   */
  name: string

  /**
   * Version string of the method or model (e.g., '2.1.0').
   */
  version?: string

  /**
   * Identifier for the specific model checkpoint used (e.g., date or hash).
   */
  modelCheckpoint?: string

  /**
   * URIs to papers, documentation, or repositories describing this method.
   */
  references?: l.UriString[]
}

export type { MethodInfo }

/** Provenance metadata describing the method used to produce an evaluation. */
const methodInfo = l.typedObject<MethodInfo>(
  $nsid,
  'methodInfo',
  l.object({
    name: l.string({ maxGraphemes: 256 }),
    version: l.optional(l.string({ maxGraphemes: 64 })),
    modelCheckpoint: l.optional(l.string({ maxGraphemes: 128 })),
    references: l.optional(
      l.array(l.string({ format: 'uri' }), { maxLength: 10 }),
    ),
  }),
)

export { methodInfo }

/** A candidate taxon identification with confidence score and rank. */
type CandidateTaxon = {
  $type?: 'app.gainforest.evaluator.defs#candidateTaxon'

  /**
   * Full scientific name of the candidate taxon.
   */
  scientificName: string

  /**
   * GBIF backbone taxonomy key for the candidate.
   */
  gbifTaxonKey?: string

  /**
   * Confidence score (0-1000, where 1000 = 100.0%).
   */
  confidence: number

  /**
   * Rank position among candidates (1 = best match).
   */
  rank: number

  /**
   * Kingdom of the candidate taxon.
   */
  kingdom?: string

  /**
   * Family of the candidate taxon.
   */
  family?: string

  /**
   * Genus of the candidate taxon.
   */
  genus?: string
}

export type { CandidateTaxon }

/** A candidate taxon identification with confidence score and rank. */
const candidateTaxon = l.typedObject<CandidateTaxon>(
  $nsid,
  'candidateTaxon',
  l.object({
    scientificName: l.string({ maxGraphemes: 512 }),
    gbifTaxonKey: l.optional(l.string({ maxGraphemes: 64 })),
    confidence: l.integer({ minimum: 0, maximum: 1000 }),
    rank: l.integer({ minimum: 1 }),
    kingdom: l.optional(l.string({ maxGraphemes: 128 })),
    family: l.optional(l.string({ maxGraphemes: 128 })),
    genus: l.optional(l.string({ maxGraphemes: 128 })),
  }),
)

export { candidateTaxon }

/** A single data quality flag indicating an issue with a specific field. */
type QualityFlag = {
  $type?: 'app.gainforest.evaluator.defs#qualityFlag'

  /**
   * The field name that has the quality issue.
   */
  field: string

  /**
   * Description of the quality issue.
   */
  issue: string

  /**
   * Severity level of the quality issue.
   */
  severity?: 'error' | 'warning' | 'info' | l.UnknownString
}

export type { QualityFlag }

/** A single data quality flag indicating an issue with a specific field. */
const qualityFlag = l.typedObject<QualityFlag>(
  $nsid,
  'qualityFlag',
  l.object({
    field: l.string({ maxGraphemes: 64 }),
    issue: l.string({ maxGraphemes: 256 }),
    severity: l.optional(
      l.string<{ maxGraphemes: 64; knownValues: ['error', 'warning', 'info'] }>(
        { maxGraphemes: 64 },
      ),
    ),
  }),
)

export { qualityFlag }

/** A single measurement derived by an evaluator from source data. */
type DerivedMeasurement = {
  $type?: 'app.gainforest.evaluator.defs#derivedMeasurement'

  /**
   * The nature of the measurement (e.g., 'canopy cover', 'NDVI', 'tree height').
   */
  measurementType: string

  /**
   * The value of the measurement.
   */
  measurementValue: string

  /**
   * The units for the measurement value (e.g., '%', 'm', 'kg').
   */
  measurementUnit?: string

  /**
   * Description of the method used to obtain the measurement.
   */
  measurementMethod?: string
}

export type { DerivedMeasurement }

/** A single measurement derived by an evaluator from source data. */
const derivedMeasurement = l.typedObject<DerivedMeasurement>(
  $nsid,
  'derivedMeasurement',
  l.object({
    measurementType: l.string({ maxGraphemes: 256 }),
    measurementValue: l.string({ maxGraphemes: 1024 }),
    measurementUnit: l.optional(l.string({ maxGraphemes: 64 })),
    measurementMethod: l.optional(l.string({ maxGraphemes: 1024 })),
  }),
)

export { derivedMeasurement }

/** AI or human species recognition result with ranked candidate identifications. */
type SpeciesIdResult = {
  $type?: 'app.gainforest.evaluator.defs#speciesIdResult'

  /**
   * Ranked list of candidate species identifications.
   */
  candidates: CandidateTaxon[]

  /**
   * Which feature of the subject record was used as input (e.g., 'mediaEvidence').
   */
  inputFeature?: string

  /**
   * Additional notes about the species identification.
   */
  remarks?: string
}

export type { SpeciesIdResult }

/** AI or human species recognition result with ranked candidate identifications. */
const speciesIdResult = l.typedObject<SpeciesIdResult>(
  $nsid,
  'speciesIdResult',
  l.object({
    candidates: l.array(l.ref<CandidateTaxon>((() => candidateTaxon) as any), {
      maxLength: 20,
    }),
    inputFeature: l.optional(l.string({ maxGraphemes: 64 })),
    remarks: l.optional(l.string({ maxGraphemes: 2048 })),
  }),
)

export { speciesIdResult }

/** Data quality assessment result with per-field quality flags. */
type DataQualityResult = {
  $type?: 'app.gainforest.evaluator.defs#dataQualityResult'

  /**
   * List of quality issues found in the record.
   */
  flags: QualityFlag[]

  /**
   * Overall completeness score (0-1000, where 1000 = 100.0%).
   */
  completenessScore?: number

  /**
   * Additional notes about the quality assessment.
   */
  remarks?: string
}

export type { DataQualityResult }

/** Data quality assessment result with per-field quality flags. */
const dataQualityResult = l.typedObject<DataQualityResult>(
  $nsid,
  'dataQualityResult',
  l.object({
    flags: l.array(l.ref<QualityFlag>((() => qualityFlag) as any), {
      maxLength: 50,
    }),
    completenessScore: l.optional(l.integer({ minimum: 0, maximum: 1000 })),
    remarks: l.optional(l.string({ maxGraphemes: 2048 })),
  }),
)

export { dataQualityResult }

/** Expert verification result for a previous identification or evaluation. */
type VerificationResult = {
  $type?: 'app.gainforest.evaluator.defs#verificationResult'

  /**
   * Verification status: confirmed, rejected, or uncertain.
   */
  status: 'confirmed' | 'rejected' | 'uncertain' | l.UnknownString

  /**
   * Name of the person who performed the verification.
   */
  verifiedBy?: string

  /**
   * Persistent identifier (e.g., ORCID) of the verifier.
   */
  verifiedByID?: string

  /**
   * Notes about the verification decision.
   */
  remarks?: string

  /**
   * Suggested corrections if the original identification was rejected or uncertain.
   */
  suggestedCorrections?: string
}

export type { VerificationResult }

/** Expert verification result for a previous identification or evaluation. */
const verificationResult = l.typedObject<VerificationResult>(
  $nsid,
  'verificationResult',
  l.object({
    status: l.string<{
      maxGraphemes: 64
      knownValues: ['confirmed', 'rejected', 'uncertain']
    }>({ maxGraphemes: 64 }),
    verifiedBy: l.optional(l.string({ maxGraphemes: 256 })),
    verifiedByID: l.optional(l.string({ maxGraphemes: 256 })),
    remarks: l.optional(l.string({ maxGraphemes: 2048 })),
    suggestedCorrections: l.optional(l.string({ maxGraphemes: 5000 })),
  }),
)

export { verificationResult }

/** Generic categorical classification result (e.g., conservation priority, habitat type). */
type ClassificationResult = {
  $type?: 'app.gainforest.evaluator.defs#classificationResult'

  /**
   * The classification category (e.g., 'conservation-priority', 'habitat-type').
   */
  category: string

  /**
   * The assigned classification value (e.g., 'critical', 'tropical-rainforest').
   */
  value: string

  /**
   * Additional notes about the classification.
   */
  remarks?: string
}

export type { ClassificationResult }

/** Generic categorical classification result (e.g., conservation priority, habitat type). */
const classificationResult = l.typedObject<ClassificationResult>(
  $nsid,
  'classificationResult',
  l.object({
    category: l.string({ maxGraphemes: 128 }),
    value: l.string({ maxGraphemes: 256 }),
    remarks: l.optional(l.string({ maxGraphemes: 2048 })),
  }),
)

export { classificationResult }

/** Derived measurements produced by an evaluator from source data (e.g., remote sensing metrics). */
type MeasurementResult = {
  $type?: 'app.gainforest.evaluator.defs#measurementResult'

  /**
   * List of derived measurements.
   */
  measurements: DerivedMeasurement[]

  /**
   * Additional notes about the measurements.
   */
  remarks?: string
}

export type { MeasurementResult }

/** Derived measurements produced by an evaluator from source data (e.g., remote sensing metrics). */
const measurementResult = l.typedObject<MeasurementResult>(
  $nsid,
  'measurementResult',
  l.object({
    measurements: l.array(
      l.ref<DerivedMeasurement>((() => derivedMeasurement) as any),
      { maxLength: 20 },
    ),
    remarks: l.optional(l.string({ maxGraphemes: 2048 })),
  }),
)

export { measurementResult }
