/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as EvaluatorDefs from './defs.defs'

const $nsid = 'app.gainforest.evaluator.service'

export { $nsid }

/** An evaluator service declaration. Publish at /app.gainforest.evaluator.service/self to declare this account as an evaluator. */
type Main = {
  $type: 'app.gainforest.evaluator.service'

  /**
   * The evaluator's policies including supported evaluation types and access model.
   */
  policies: EvaluatorPolicies

  /**
   * Timestamp of when this evaluator service was declared.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** An evaluator service declaration. Publish at /app.gainforest.evaluator.service/self to declare this account as an evaluator. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    policies: l.ref<EvaluatorPolicies>((() => evaluatorPolicies) as any),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Policies declaring what this evaluator does and how it operates. */
type EvaluatorPolicies = {
  $type?: 'app.gainforest.evaluator.service#evaluatorPolicies'

  /**
   * Whether this evaluator requires user subscription ('subscription') or processes all matching records ('open').
   */
  accessModel?: 'open' | 'subscription' | l.UnknownString

  /**
   * List of evaluation type identifiers this evaluator produces (e.g., 'species-id', 'data-quality').
   */
  evaluationTypes: string[]

  /**
   * Detailed definitions for each evaluation type, including human-readable descriptions.
   */
  evaluationTypeDefinitions?: EvaluationTypeDefinition[]

  /**
   * NSIDs of record collections this evaluator can evaluate (e.g., 'app.gainforest.dwc.occurrence').
   */
  subjectCollections?: string[]
}

export type { EvaluatorPolicies }

/** Policies declaring what this evaluator does and how it operates. */
const evaluatorPolicies = l.typedObject<EvaluatorPolicies>(
  $nsid,
  'evaluatorPolicies',
  l.object({
    accessModel: l.optional(
      l.string<{ maxGraphemes: 64; knownValues: ['open', 'subscription'] }>({
        maxGraphemes: 64,
      }),
    ),
    evaluationTypes: l.array(l.string({ maxGraphemes: 64 }), { maxLength: 20 }),
    evaluationTypeDefinitions: l.optional(
      l.array(
        l.ref<EvaluationTypeDefinition>(
          (() => evaluationTypeDefinition) as any,
        ),
        { maxLength: 20 },
      ),
    ),
    subjectCollections: l.optional(
      l.array(l.string({ maxGraphemes: 128 }), { maxLength: 20 }),
    ),
  }),
)

export { evaluatorPolicies }

/** Definition of a single evaluation type produced by this evaluator. */
type EvaluationTypeDefinition = {
  $type?: 'app.gainforest.evaluator.service#evaluationTypeDefinition'

  /**
   * The evaluation type identifier (must match an entry in evaluationTypes).
   */
  identifier: string

  /**
   * The lexicon reference for the result type (e.g., 'app.gainforest.evaluator.defs#speciesIdResult').
   */
  resultType: string

  /**
   * Default method info for this evaluation type (can be overridden per-evaluation).
   */
  method?: EvaluatorDefs.MethodInfo

  /**
   * Human-readable names and descriptions in various languages.
   */
  locales?: EvaluationTypeLocale[]
}

export type { EvaluationTypeDefinition }

/** Definition of a single evaluation type produced by this evaluator. */
const evaluationTypeDefinition = l.typedObject<EvaluationTypeDefinition>(
  $nsid,
  'evaluationTypeDefinition',
  l.object({
    identifier: l.string({ maxGraphemes: 64 }),
    resultType: l.string({ maxGraphemes: 128 }),
    method: l.optional(
      l.ref<EvaluatorDefs.MethodInfo>((() => EvaluatorDefs.methodInfo) as any),
    ),
    locales: l.optional(
      l.array(
        l.ref<EvaluationTypeLocale>((() => evaluationTypeLocale) as any),
        { maxLength: 20 },
      ),
    ),
  }),
)

export { evaluationTypeDefinition }

/** Localized name and description for an evaluation type. */
type EvaluationTypeLocale = {
  $type?: 'app.gainforest.evaluator.service#evaluationTypeLocale'

  /**
   * Language code (BCP-47, e.g., 'en', 'pt-BR').
   */
  lang: string

  /**
   * Short human-readable name for this evaluation type.
   */
  name: string

  /**
   * Longer description of what this evaluation type does.
   */
  description: string
}

export type { EvaluationTypeLocale }

/** Localized name and description for an evaluation type. */
const evaluationTypeLocale = l.typedObject<EvaluationTypeLocale>(
  $nsid,
  'evaluationTypeLocale',
  l.object({
    lang: l.string({ maxGraphemes: 16 }),
    name: l.string({ maxGraphemes: 128 }),
    description: l.string({ maxGraphemes: 2048 }),
  }),
)

export { evaluationTypeLocale }
