/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.gainforest.evaluator.subscription'

export { $nsid }

/** User subscription to an evaluator service. Published by the user (not the evaluator) to declare they want evaluations. */
type Main = {
  $type: 'app.gainforest.evaluator.subscription'

  /**
   * DID of the evaluator service to subscribe to.
   */
  evaluator: l.DidString

  /**
   * Which of the user's record collections should be evaluated (NSIDs). Must be a subset of the evaluator's subjectCollections. If omitted, all supported collections are evaluated.
   */
  collections?: string[]

  /**
   * Which evaluation types the user wants. If omitted, all types the evaluator supports are applied.
   */
  evaluationTypes?: string[]

  /**
   * Timestamp of when this subscription was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** User subscription to an evaluator service. Published by the user (not the evaluator) to declare they want evaluations. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    evaluator: l.string({ format: 'did' }),
    collections: l.optional(
      l.array(l.string({ maxGraphemes: 128 }), { maxLength: 20 }),
    ),
    evaluationTypes: l.optional(
      l.array(l.string({ maxGraphemes: 64 }), { maxLength: 20 }),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
