/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs'
import * as HypercertsDefs from '../hypercerts/defs.defs'
import * as ClaimActivity from '../hypercerts/claim/activity.defs'

const $nsid = 'org.hyperboards.board'

export { $nsid }

/** Configuration record for a hyperboard, wrapping an underlying activity or collection with visual presentation settings. Stored in the creator's PDS. */
type Main = {
  $type: 'org.hyperboards.board'

  /**
   * Reference to the org.hypercerts.claim.activity or org.hypercerts.claim.collection this board visualizes.
   */
  subject: RepoStrongRef.Main

  /**
   * Board-level visual configuration (background, colors, aspect ratio).
   */
  config?: BoardConfig

  /**
   * Per-contributor configuration entries for this board.
   */
  contributorConfigs?: ContributorConfig[]

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Configuration record for a hyperboard, wrapping an underlying activity or collection with visual presentation settings. Stored in the creator's PDS. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subject: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    config: l.optional(l.ref<BoardConfig>((() => boardConfig) as any)),
    contributorConfigs: l.optional(
      l.array(l.ref<ContributorConfig>((() => contributorConfig) as any), {
        maxLength: 1000,
      }),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Visual configuration for a hyperboard's background, colors, and layout. */
type BoardConfig = {
  $type?: 'org.hyperboards.board#boardConfig'

  /**
   * Type of background content.
   */
  backgroundType?: 'image' | 'iframe' | l.UnknownString

  /**
   * Background image as a URI or image blob.
   */
  backgroundImage?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * URI of the background iframe.
   */
  backgroundIframeUrl?: l.UriString

  /**
   * Whether the background is rendered in grayscale. Default: true.
   */
  backgroundGrayscale?: boolean

  /**
   * Background opacity as a percentage (0–100).
   */
  backgroundOpacity?: number

  /**
   * Background color as a hex string (e.g. '#ffffff').
   */
  backgroundColor?: string

  /**
   * Border color as a hex string (e.g. '#000000').
   */
  borderColor?: string

  /**
   * Whether contributor images are rendered in grayscale. Default: false.
   */
  grayscaleImages?: boolean

  /**
   * Shape used to crop contributor images on this board.
   */
  imageShape?: 'circular' | 'square' | l.UnknownString

  /**
   * Display aspect ratio of the board.
   */
  aspectRatio?: '16:9' | '4:3' | '1:1' | l.UnknownString
}

export type { BoardConfig }

/** Visual configuration for a hyperboard's background, colors, and layout. */
const boardConfig = l.typedObject<BoardConfig>(
  $nsid,
  'boardConfig',
  l.object({
    backgroundType: l.optional(
      l.string<{ knownValues: ['image', 'iframe']; maxLength: 10 }>({
        maxLength: 10,
      }),
    ),
    backgroundImage: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    backgroundIframeUrl: l.optional(
      l.string({ format: 'uri', maxLength: 2048 }),
    ),
    backgroundGrayscale: l.optional(l.boolean()),
    backgroundOpacity: l.optional(l.integer({ minimum: 0, maximum: 100 })),
    backgroundColor: l.optional(l.string({ maxLength: 20 })),
    borderColor: l.optional(l.string({ maxLength: 20 })),
    grayscaleImages: l.optional(l.boolean()),
    imageShape: l.optional(
      l.string<{ knownValues: ['circular', 'square']; maxLength: 20 }>({
        maxLength: 20,
      }),
    ),
    aspectRatio: l.optional(
      l.string<{ knownValues: ['16:9', '4:3', '1:1']; maxLength: 10 }>({
        maxLength: 10,
      }),
    ),
  }),
)

export { boardConfig }

/** Configuration for a specific contributor within a board. Values serve as fallbacks when the contributor has not defined them on their profile. It can also be used to override contributor settings on this board without changing their global profile. */
type ContributorConfig = {
  $type?: 'org.hyperboards.board#contributorConfig'

  /**
   * Identifies the contributor being styled. A strong reference to an org.hypercerts.claim.contributorInformation record, or a contributorIdentity (DID or identifier string) for contributors without a dedicated record.
   */
  contributor:
    | l.$Typed<RepoStrongRef.Main>
    | l.$Typed<ClaimActivity.ContributorIdentity>
    | l.Unknown$TypedObject

  /**
   * When true, these values take precedence over the contributor's own profile and display settings. When false or omitted, they are only used as fallbacks if the contributor has not set their own settings.
   */
  override?: boolean

  /**
   * Display name for this contributor on this board.
   */
  displayName?: string

  /**
   * Avatar or face image for this contributor on this board, as a URI or image blob.
   */
  image?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Video for this contributor, as a URI (embed/direct link) or uploaded video blob.
   */
  video?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallVideo>
    | l.Unknown$TypedObject

  /**
   * Image overlay shown when hovering over this contributor, as a URI or image blob.
   */
  hoverImage?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Iframe overlay shown when hovering over this contributor.
   */
  hoverIframeUrl?: l.UriString

  /**
   * Click-through link URL for this contributor.
   */
  url?: l.UriString
}

export type { ContributorConfig }

/** Configuration for a specific contributor within a board. Values serve as fallbacks when the contributor has not defined them on their profile. It can also be used to override contributor settings on this board without changing their global profile. */
const contributorConfig = l.typedObject<ContributorConfig>(
  $nsid,
  'contributorConfig',
  l.object({
    contributor: l.typedUnion(
      [
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        l.typedRef<ClaimActivity.ContributorIdentity>(
          (() => ClaimActivity.contributorIdentity) as any,
        ),
      ],
      false,
    ),
    override: l.optional(l.boolean()),
    displayName: l.optional(l.string({ maxLength: 640, maxGraphemes: 64 })),
    image: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    video: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallVideo>(
            (() => HypercertsDefs.smallVideo) as any,
          ),
        ],
        false,
      ),
    ),
    hoverImage: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    hoverIframeUrl: l.optional(l.string({ format: 'uri', maxLength: 2048 })),
    url: l.optional(l.string({ format: 'uri', maxLength: 2048 })),
  }),
)

export { contributorConfig }
