/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HypercertsDefs from '../hypercerts/defs.defs'

const $nsid = 'org.hyperboards.displayProfile'

export { $nsid }

/** User-declared visual presentation defaults for how a contributor appears on hyperboards. Stored in the contributor's own PDS and reusable across multiple boards. */
type Main = {
  $type: 'org.hyperboards.displayProfile'

  /**
   * Display name override for this user on hyperboards.
   */
  displayName?: string

  /**
   * Avatar or face image override for this user on hyperboards, as a URI or image blob.
   */
  image?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Default video for this user across boards, as a URI (embed/direct link) or uploaded video blob.
   */
  video?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallVideo>
    | l.Unknown$TypedObject

  /**
   * Default hover image for this user across boards, as a URI or image blob.
   */
  hoverImage?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallImage>
    | l.Unknown$TypedObject

  /**
   * Default hover iframe URL for this user across boards.
   */
  hoverIframeUrl?: l.UriString

  /**
   * Default click-through link URL for this user across boards.
   */
  url?: l.UriString

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** User-declared visual presentation defaults for how a contributor appears on hyperboards. Stored in the contributor's own PDS and reusable across multiple boards. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    displayName: l.optional(l.string({ maxLength: 640, maxGraphemes: 64 })),
    image: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    video: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallVideo>(
            (() => HypercertsDefs.smallVideo) as any,
          ),
        ],
        false,
      ),
    ),
    hoverImage: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallImage>(
            (() => HypercertsDefs.smallImage) as any,
          ),
        ],
        false,
      ),
    ),
    hoverIframeUrl: l.optional(l.string({ format: 'uri', maxLength: 2048 })),
    url: l.optional(l.string({ format: 'uri', maxLength: 2048 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
