/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'

const $nsid = 'org.hypercerts.workscope.cel'

export { $nsid }

/** A structured, machine-evaluable work scope definition using CEL (Common Expression Language). Tags referenced in the expression correspond to org.hypercerts.workscope.tag keys. See https://github.com/google/cel-spec. Note: this is intentionally type 'object' (not 'record') so it can be directly embedded inline in union types (e.g., activity.workScope) without requiring a separate collection or strongRef indirection. */
type Main = {
  $type?: 'org.hypercerts.workscope.cel'

  /**
   * A CEL expression encoding the work scope conditions. Example: scope.hasAll(['mangrove_restoration', 'environmental_education']) && location.country == 'KE'
   */
  expression: string

  /**
   * Strong references to org.hypercerts.workscope.tag records used in the expression. Enables fast indexing by AT-URI and provides referential integrity to the underlying tag records.
   */
  usedTags: RepoStrongRef.Main[]

  /**
   * CEL context schema version.
   */
  version: 'v1' | l.UnknownString

  /**
   * Client-declared timestamp when this expression was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A structured, machine-evaluable work scope definition using CEL (Common Expression Language). Tags referenced in the expression correspond to org.hypercerts.workscope.tag keys. See https://github.com/google/cel-spec. Note: this is intentionally type 'object' (not 'record') so it can be directly embedded inline in union types (e.g., activity.workScope) without requiring a separate collection or strongRef indirection. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    expression: l.string({ maxLength: 10000, maxGraphemes: 5000 }),
    usedTags: l.array(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
      { maxLength: 100 },
    ),
    version: l.string<{ maxLength: 16; knownValues: ['v1'] }>({
      maxLength: 16,
    }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
