/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs'
import * as HypercertsDefs from '../defs.defs'

const $nsid = 'org.hypercerts.workscope.tag'

export { $nsid }

/** A reusable scope atom for work scope logic expressions. Scopes can represent topics, languages, domains, deliverables, methods, regions, tags, or other categorical labels. Tags are composed into structured expressions via CEL (Common Expression Language) on activity records. */
type Main = {
  $type: 'org.hypercerts.workscope.tag'

  /**
   * Lowercase, underscore-separated machine-readable key for this scope (e.g., 'mangrove_restoration', 'biodiversity_monitoring'). Used as the canonical identifier in CEL expressions.
   */
  key: string

  /**
   * Human-readable name for this scope.
   */
  name: string

  /**
   * Category type of this scope.
   */
  category?: 'topic' | 'language' | 'domain' | 'method' | l.UnknownString

  /**
   * Optional longer description of this scope.
   */
  description?: string

  /**
   * Optional strong reference to a parent work scope tag record for taxonomy/hierarchy support. The record referenced must conform with the lexicon org.hypercerts.workscope.tag.
   */
  parent?: RepoStrongRef.Main

  /**
   * Lifecycle status of this tag. Communities propose tags, curators accept them,
   *
   * @deprecated tags point to replacements via supersededBy.
   */
  status?: 'proposed' | 'accepted' | 'deprecated' | l.UnknownString

  /**
   * When status is '
   *
   * @deprecated ', points to the replacement work scope tag record. The record referenced must conform with the lexicon org.hypercerts.workscope.tag.
   */
  supersededBy?: RepoStrongRef.Main

  /**
   * Alternative human-readable names for this scope (e.g., translations, abbreviations, or common synonyms). Unlike sameAs, these are plain-text labels, not links to external ontologies.
   */
  aliases?: string[]

  /**
   * URIs to semantically equivalent concepts in external ontologies or taxonomies (e.g., Wikidata QIDs, ENVO terms, SDG targets). Used for interoperability, not as documentation.
   */
  sameAs?: l.UriString[]

  /**
   * Link to a governance or reference document where this work scope tag is defined and further explained.
   */
  referenceDocument?:
    | l.$Typed<HypercertsDefs.Uri>
    | l.$Typed<HypercertsDefs.SmallBlob>
    | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A reusable scope atom for work scope logic expressions. Scopes can represent topics, languages, domains, deliverables, methods, regions, tags, or other categorical labels. Tags are composed into structured expressions via CEL (Common Expression Language) on activity records. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    key: l.string({ maxLength: 120 }),
    name: l.string({ maxLength: 200 }),
    category: l.optional(
      l.string<{
        knownValues: ['topic', 'language', 'domain', 'method']
        maxLength: 50
      }>({ maxLength: 50 }),
    ),
    description: l.optional(l.string({ maxLength: 10000, maxGraphemes: 1000 })),
    parent: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    status: l.optional(
      l.string<{
        knownValues: ['proposed', 'accepted', 'deprecated']
        maxLength: 20
      }>({ maxLength: 20 }),
    ),
    supersededBy: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    aliases: l.optional(
      l.array(l.string({ maxLength: 200 }), { maxLength: 50 }),
    ),
    sameAs: l.optional(
      l.array(l.string({ format: 'uri', maxLength: 2048 }), { maxLength: 20 }),
    ),
    referenceDocument: l.optional(
      l.typedUnion(
        [
          l.typedRef<HypercertsDefs.Uri>((() => HypercertsDefs.uri) as any),
          l.typedRef<HypercertsDefs.SmallBlob>(
            (() => HypercertsDefs.smallBlob) as any,
          ),
        ],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
