/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.impactindexer.link.attestation'

export { $nsid }

/** An attestation linking an ATProto DID to an EVM wallet address, signed with EIP-712. */
type Main = {
  $type: 'org.impactindexer.link.attestation'

  /**
   * The EVM wallet address (checksummed or lowercase, 0x-prefixed)
   */
  address: string

  /**
   * The EVM chain ID where the signature was created
   */
  chainId: number

  /**
   * The EIP-712 signature in hex format (0x-prefixed, 65 bytes for ECDSA, longer for smart contract sigs)
   */
  signature: string

  /**
   * The EIP-712 typed data message that was signed
   */
  message: Eip712Message

  /**
   * The type of signature: eoa (EOA/ECDSA), erc1271 (smart contract), erc6492 (counterfactual)
   */
  signatureType: 'eoa' | 'erc1271' | 'erc6492' | l.UnknownString

  /**
   * Timestamp when the attestation was created
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** An attestation linking an ATProto DID to an EVM wallet address, signed with EIP-712. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    address: l.string({ minLength: 42, maxLength: 42 }),
    chainId: l.integer({ minimum: 1 }),
    signature: l.string({ minLength: 132, maxLength: 1000 }),
    message: l.ref<Eip712Message>((() => eip712Message) as any),
    signatureType: l.string<{
      maxLength: 10
      knownValues: ['eoa', 'erc1271', 'erc6492']
    }>({ maxLength: 10 }),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** The EIP-712 typed data message structure */
type Eip712Message = {
  $type?: 'org.impactindexer.link.attestation#eip712Message'

  /**
   * The ATProto DID being linked
   */
  did: string

  /**
   * The EVM address being linked (0x-prefixed)
   */
  evmAddress: string

  /**
   * The chain ID as a string (for bigint compatibility, max uint256)
   */
  chainId: string

  /**
   * Unix timestamp as a string (for bigint compatibility)
   */
  timestamp: string

  /**
   * Replay protection nonce as a string (for bigint compatibility)
   */
  nonce: string
}

export type { Eip712Message }

/** The EIP-712 typed data message structure */
const eip712Message = l.typedObject<Eip712Message>(
  $nsid,
  'eip712Message',
  l.object({
    did: l.string({ maxLength: 2048 }),
    evmAddress: l.string({ minLength: 42, maxLength: 42 }),
    chainId: l.string({ maxLength: 78 }),
    timestamp: l.string({ maxLength: 78 }),
    nonce: l.string({ maxLength: 78 }),
  }),
)

export { eip712Message }
