/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from '../../bsky/richtext/facet.defs'

const $nsid = 'app.gainforest.common.defs'

export { $nsid }

/** An object that contains the text and an object that defins and enables richtext formatting on the text. */
type Richtext = {
  $type?: 'app.gainforest.common.defs#richtext'

  /**
   * The text to be formatted
   */
  text: string
  facets?: RichtextFacet.Main[]
}

export type { Richtext }

/** An object that contains the text and an object that defins and enables richtext formatting on the text. */
const richtext = l.typedObject<Richtext>(
  $nsid,
  'richtext',
  l.object({
    text: l.string(),
    facets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
  }),
)

export { richtext }

/** Reference to external data via URI */
type Uri = {
  $type?: 'app.gainforest.common.defs#uri'

  /**
   * URI to external resource
   */
  uri: l.UriString
}

export type { Uri }

/** Reference to external data via URI */
const uri = l.typedObject<Uri>(
  $nsid,
  'uri',
  l.object({ uri: l.string({ format: 'uri', maxGraphemes: 1024 }) }),
)

export { uri }

/** Image file for photos, camera traps, drone stills, scanned documents */
type Image = {
  $type?: 'app.gainforest.common.defs#image'

  /**
   * Image up to 20MB. Supports JPEG, PNG, WebP, HEIC (phones), TIFF (scientific), GIF, BMP, SVG.
   */
  file: l.BlobRef
}

export type { Image }

/** Image file for photos, camera traps, drone stills, scanned documents */
const image = l.typedObject<Image>(
  $nsid,
  'image',
  l.object({
    file: l.blob({
      accept: [
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp',
        'image/heic',
        'image/heif',
        'image/tiff',
        'image/tif',
        'image/gif',
        'image/bmp',
        'image/svg+xml',
      ],
      maxSize: 20971520,
      allowLegacy: false,
    }),
  }),
)

export { image }

/** Small image for thumbnails and previews */
type ImageThumbnail = {
  $type?: 'app.gainforest.common.defs#imageThumbnail'

  /**
   * Thumbnail image up to 1MB
   */
  file: l.BlobRef
}

export type { ImageThumbnail }

/** Small image for thumbnails and previews */
const imageThumbnail = l.typedObject<ImageThumbnail>(
  $nsid,
  'imageThumbnail',
  l.object({
    file: l.blob({
      accept: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
      maxSize: 1048576,
      allowLegacy: false,
    }),
  }),
)

export { imageThumbnail }

/** Video file for camera traps, drone footage, underwater video, behavioral observations */
type Video = {
  $type?: 'app.gainforest.common.defs#video'

  /**
   * Video up to 100MB. Supports MP4, MOV, AVI, WebM, MKV, MPEG, 3GP.
   */
  file: l.BlobRef
}

export type { Video }

/** Video file for camera traps, drone footage, underwater video, behavioral observations */
const video = l.typedObject<Video>(
  $nsid,
  'video',
  l.object({
    file: l.blob({
      accept: [
        'video/mp4',
        'video/quicktime',
        'video/x-msvideo',
        'video/webm',
        'video/x-matroska',
        'video/mpeg',
        'video/3gpp',
        'video/3gpp2',
      ],
      maxSize: 104857600,
      allowLegacy: false,
    }),
  }),
)

export { video }

/** Audio file for bioacoustics, soundscapes, field recordings, species calls */
type Audio = {
  $type?: 'app.gainforest.common.defs#audio'

  /**
   * Audio up to 100MB. Supports WAV, MP3, M4A, AAC, FLAC, OGG, Opus, WebM, AIFF.
   */
  file: l.BlobRef
}

export type { Audio }

/** Audio file for bioacoustics, soundscapes, field recordings, species calls */
const audio = l.typedObject<Audio>(
  $nsid,
  'audio',
  l.object({
    file: l.blob({
      accept: [
        'audio/wav',
        'audio/vnd.wave',
        'audio/x-wav',
        'audio/mpeg',
        'audio/mp3',
        'audio/mp4',
        'audio/x-m4a',
        'audio/aac',
        'audio/flac',
        'audio/x-flac',
        'audio/ogg',
        'audio/opus',
        'audio/webm',
        'audio/aiff',
        'audio/x-aiff',
      ],
      maxSize: 104857600,
      allowLegacy: false,
    }),
  }),
)

export { audio }

/** Spectrogram image - visual representation of audio frequency content */
type Spectrogram = {
  $type?: 'app.gainforest.common.defs#spectrogram'

  /**
   * Spectrogram image up to 5MB
   */
  file: l.BlobRef
}

export type { Spectrogram }

/** Spectrogram image - visual representation of audio frequency content */
const spectrogram = l.typedObject<Spectrogram>(
  $nsid,
  'spectrogram',
  l.object({
    file: l.blob({
      accept: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
      maxSize: 5242880,
      allowLegacy: false,
    }),
  }),
)

export { spectrogram }

/** Document file for reports, field notes, permits, publications */
type Document = {
  $type?: 'app.gainforest.common.defs#document'

  /**
   * Document up to 20MB. Supports PDF, TXT, Markdown, HTML, RTF, DOC, DOCX.
   */
  file: l.BlobRef
}

export type { Document }

/** Document file for reports, field notes, permits, publications */
const document = l.typedObject<Document>(
  $nsid,
  'document',
  l.object({
    file: l.blob({
      accept: [
        'application/pdf',
        'text/plain',
        'text/markdown',
        'text/html',
        'application/rtf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      ],
      maxSize: 20971520,
      allowLegacy: false,
    }),
  }),
)

export { document }

/** Structured data file for observations, measurements, exports */
type DataFile = {
  $type?: 'app.gainforest.common.defs#dataFile'

  /**
   * Data file up to 50MB. Supports CSV, TSV, JSON, JSON-LD, XML, XLS, XLSX, ODS.
   */
  file: l.BlobRef
}

export type { DataFile }

/** Structured data file for observations, measurements, exports */
const dataFile = l.typedObject<DataFile>(
  $nsid,
  'dataFile',
  l.object({
    file: l.blob({
      accept: [
        'text/csv',
        'text/tab-separated-values',
        'application/json',
        'application/ld+json',
        'application/xml',
        'text/xml',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.oasis.opendocument.spreadsheet',
      ],
      maxSize: 52428800,
      allowLegacy: false,
    }),
  }),
)

export { dataFile }

/** GPS track file for transects, survey routes, patrol paths */
type GpsTrack = {
  $type?: 'app.gainforest.common.defs#gpsTrack'

  /**
   * GPS track up to 10MB. Supports GPX, KML, KMZ, GeoJSON.
   */
  file: l.BlobRef
}

export type { GpsTrack }

/** GPS track file for transects, survey routes, patrol paths */
const gpsTrack = l.typedObject<GpsTrack>(
  $nsid,
  'gpsTrack',
  l.object({
    file: l.blob({
      accept: [
        'application/gpx+xml',
        'application/vnd.google-earth.kml+xml',
        'application/vnd.google-earth.kmz',
        'application/geo+json',
        'application/json',
      ],
      maxSize: 10485760,
      allowLegacy: false,
    }),
  }),
)

export { gpsTrack }

/** Geospatial data file for maps, boundaries, habitat layers */
type Geospatial = {
  $type?: 'app.gainforest.common.defs#geospatial'

  /**
   * Geospatial data up to 100MB. Supports GeoJSON, KML, KMZ, GeoPackage, Shapefile (zipped), GeoTIFF.
   */
  file: l.BlobRef
}

export type { Geospatial }

/** Geospatial data file for maps, boundaries, habitat layers */
const geospatial = l.typedObject<Geospatial>(
  $nsid,
  'geospatial',
  l.object({
    file: l.blob({
      accept: [
        'application/geo+json',
        'application/json',
        'application/vnd.google-earth.kml+xml',
        'application/vnd.google-earth.kmz',
        'application/geopackage+sqlite3',
        'application/x-shapefile',
        'application/zip',
        'image/tiff',
        'image/geotiff',
      ],
      maxSize: 104857600,
      allowLegacy: false,
    }),
  }),
)

export { geospatial }

/** Sensor data file for environmental monitoring (temperature, humidity, light, etc.) */
type SensorData = {
  $type?: 'app.gainforest.common.defs#sensorData'

  /**
   * Sensor data up to 50MB. Supports CSV, JSON, TXT, NetCDF, HDF5.
   */
  file: l.BlobRef
}

export type { SensorData }

/** Sensor data file for environmental monitoring (temperature, humidity, light, etc.) */
const sensorData = l.typedObject<SensorData>(
  $nsid,
  'sensorData',
  l.object({
    file: l.blob({
      accept: [
        'text/csv',
        'application/json',
        'text/plain',
        'application/x-netcdf',
        'application/x-hdf5',
      ],
      maxSize: 52428800,
      allowLegacy: false,
    }),
  }),
)

export { sensorData }

/** Genetic/genomic data file for eDNA, barcoding, sequencing results */
type GeneticData = {
  $type?: 'app.gainforest.common.defs#geneticData'

  /**
   * Genetic data up to 100MB. Supports FASTA, FASTQ, CSV, JSON.
   */
  file: l.BlobRef
}

export type { GeneticData }

/** Genetic/genomic data file for eDNA, barcoding, sequencing results */
const geneticData = l.typedObject<GeneticData>(
  $nsid,
  'geneticData',
  l.object({
    file: l.blob({
      accept: [
        'text/x-fasta',
        'application/x-fasta',
        'text/x-fastq',
        'application/x-fastq',
        'text/plain',
        'text/csv',
        'application/json',
      ],
      maxSize: 104857600,
      allowLegacy: false,
    }),
  }),
)

export { geneticData }

/** Reference to an indexed organization */
type IndexedOrganization = {
  $type?: 'app.gainforest.common.defs#indexedOrganization'

  /**
   * The URI of the organization
   */
  id: l.UriString

  /**
   * The name of the organization
   */
  name: string
}

export type { IndexedOrganization }

/** Reference to an indexed organization */
const indexedOrganization = l.typedObject<IndexedOrganization>(
  $nsid,
  'indexedOrganization',
  l.object({ id: l.string({ format: 'uri' }), name: l.string() }),
)

export { indexedOrganization }
